
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model RolePermission
 * 
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model BiFolder
 * 
 */
export type BiFolder = Prisma.BiFolderModel
/**
 * Model BiDashboard
 * 
 */
export type BiDashboard = Prisma.BiDashboardModel
/**
 * Model BiDashboardMember
 * 
 */
export type BiDashboardMember = Prisma.BiDashboardMemberModel
/**
 * Model BiDataset
 * 
 */
export type BiDataset = Prisma.BiDatasetModel
/**
 * Model BiSource
 * 
 */
export type BiSource = Prisma.BiSourceModel
/**
 * Model BiPanel
 * 
 */
export type BiPanel = Prisma.BiPanelModel
/**
 * Model BiFilter
 * 
 */
export type BiFilter = Prisma.BiFilterModel
