
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AccountProvider = {
  credential: 'credential',
  google: 'google',
  github: 'github'
} as const

export type AccountProvider = (typeof AccountProvider)[keyof typeof AccountProvider]


export const BiRole = {
  VIEWER: 'VIEWER',
  EDITOR: 'EDITOR'
} as const

export type BiRole = (typeof BiRole)[keyof typeof BiRole]
