
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BiDataSet` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BiDataSet
 * 
 */
export type BiDataSetModel = runtime.Types.Result.DefaultSelection<Prisma.$BiDataSetPayload>

export type AggregateBiDataSet = {
  _count: BiDataSetCountAggregateOutputType | null
  _min: BiDataSetMinAggregateOutputType | null
  _max: BiDataSetMaxAggregateOutputType | null
}

export type BiDataSetMinAggregateOutputType = {
  id: string | null
  name: string | null
  sql: string | null
  description: string | null
  isPublic: boolean | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type BiDataSetMaxAggregateOutputType = {
  id: string | null
  name: string | null
  sql: string | null
  description: string | null
  isPublic: boolean | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type BiDataSetCountAggregateOutputType = {
  id: number
  name: number
  sql: number
  description: number
  isPublic: number
  lastRunAt: number
  createdAt: number
  updatedAt: number
  userId: number
  _all: number
}


export type BiDataSetMinAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type BiDataSetMaxAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type BiDataSetCountAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  _all?: true
}

export type BiDataSetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiDataSet to aggregate.
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDataSets to fetch.
   */
  orderBy?: Prisma.BiDataSetOrderByWithRelationInput | Prisma.BiDataSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BiDataSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDataSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDataSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BiDataSets
  **/
  _count?: true | BiDataSetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BiDataSetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BiDataSetMaxAggregateInputType
}

export type GetBiDataSetAggregateType<T extends BiDataSetAggregateArgs> = {
      [P in keyof T & keyof AggregateBiDataSet]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBiDataSet[P]>
    : Prisma.GetScalarType<T[P], AggregateBiDataSet[P]>
}




export type BiDataSetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDataSetWhereInput
  orderBy?: Prisma.BiDataSetOrderByWithAggregationInput | Prisma.BiDataSetOrderByWithAggregationInput[]
  by: Prisma.BiDataSetScalarFieldEnum[] | Prisma.BiDataSetScalarFieldEnum
  having?: Prisma.BiDataSetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BiDataSetCountAggregateInputType | true
  _min?: BiDataSetMinAggregateInputType
  _max?: BiDataSetMaxAggregateInputType
}

export type BiDataSetGroupByOutputType = {
  id: string
  name: string
  sql: string
  description: string | null
  isPublic: boolean
  lastRunAt: Date | null
  createdAt: Date
  updatedAt: Date
  userId: string | null
  _count: BiDataSetCountAggregateOutputType | null
  _min: BiDataSetMinAggregateOutputType | null
  _max: BiDataSetMaxAggregateOutputType | null
}

export type GetBiDataSetGroupByPayload<T extends BiDataSetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BiDataSetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BiDataSetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BiDataSetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BiDataSetGroupByOutputType[P]>
      }
    >
  >



export type BiDataSetWhereInput = {
  AND?: Prisma.BiDataSetWhereInput | Prisma.BiDataSetWhereInput[]
  OR?: Prisma.BiDataSetWhereInput[]
  NOT?: Prisma.BiDataSetWhereInput | Prisma.BiDataSetWhereInput[]
  id?: Prisma.StringFilter<"BiDataSet"> | string
  name?: Prisma.StringFilter<"BiDataSet"> | string
  sql?: Prisma.StringFilter<"BiDataSet"> | string
  description?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataSet"> | boolean
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataSet"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
  panels?: Prisma.BiPanelListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type BiDataSetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  panels?: Prisma.BiPanelOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type BiDataSetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BiDataSetWhereInput | Prisma.BiDataSetWhereInput[]
  OR?: Prisma.BiDataSetWhereInput[]
  NOT?: Prisma.BiDataSetWhereInput | Prisma.BiDataSetWhereInput[]
  name?: Prisma.StringFilter<"BiDataSet"> | string
  sql?: Prisma.StringFilter<"BiDataSet"> | string
  description?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataSet"> | boolean
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataSet"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
  panels?: Prisma.BiPanelListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type BiDataSetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BiDataSetCountOrderByAggregateInput
  _max?: Prisma.BiDataSetMaxOrderByAggregateInput
  _min?: Prisma.BiDataSetMinOrderByAggregateInput
}

export type BiDataSetScalarWhereWithAggregatesInput = {
  AND?: Prisma.BiDataSetScalarWhereWithAggregatesInput | Prisma.BiDataSetScalarWhereWithAggregatesInput[]
  OR?: Prisma.BiDataSetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BiDataSetScalarWhereWithAggregatesInput | Prisma.BiDataSetScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BiDataSet"> | string
  name?: Prisma.StringWithAggregatesFilter<"BiDataSet"> | string
  sql?: Prisma.StringWithAggregatesFilter<"BiDataSet"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"BiDataSet"> | string | null
  isPublic?: Prisma.BoolWithAggregatesFilter<"BiDataSet"> | boolean
  lastRunAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BiDataSet"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BiDataSet"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BiDataSet"> | Date | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"BiDataSet"> | string | null
}

export type BiDataSetCreateInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  panels?: Prisma.BiPanelCreateNestedManyWithoutDataSetInput
  user?: Prisma.UserCreateNestedOneWithoutBiDataSetsInput
}

export type BiDataSetUncheckedCreateInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
  panels?: Prisma.BiPanelUncheckedCreateNestedManyWithoutDataSetInput
}

export type BiDataSetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  panels?: Prisma.BiPanelUpdateManyWithoutDataSetNestedInput
  user?: Prisma.UserUpdateOneWithoutBiDataSetsNestedInput
}

export type BiDataSetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  panels?: Prisma.BiPanelUncheckedUpdateManyWithoutDataSetNestedInput
}

export type BiDataSetCreateManyInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
}

export type BiDataSetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiDataSetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BiDataSetListRelationFilter = {
  every?: Prisma.BiDataSetWhereInput
  some?: Prisma.BiDataSetWhereInput
  none?: Prisma.BiDataSetWhereInput
}

export type BiDataSetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BiDataSetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDataSetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDataSetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDataSetNullableScalarRelationFilter = {
  is?: Prisma.BiDataSetWhereInput | null
  isNot?: Prisma.BiDataSetWhereInput | null
}

export type BiDataSetCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput> | Prisma.BiDataSetCreateWithoutUserInput[] | Prisma.BiDataSetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutUserInput | Prisma.BiDataSetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BiDataSetCreateManyUserInputEnvelope
  connect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
}

export type BiDataSetUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput> | Prisma.BiDataSetCreateWithoutUserInput[] | Prisma.BiDataSetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutUserInput | Prisma.BiDataSetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BiDataSetCreateManyUserInputEnvelope
  connect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
}

export type BiDataSetUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput> | Prisma.BiDataSetCreateWithoutUserInput[] | Prisma.BiDataSetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutUserInput | Prisma.BiDataSetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BiDataSetUpsertWithWhereUniqueWithoutUserInput | Prisma.BiDataSetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BiDataSetCreateManyUserInputEnvelope
  set?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  disconnect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  delete?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  connect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  update?: Prisma.BiDataSetUpdateWithWhereUniqueWithoutUserInput | Prisma.BiDataSetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BiDataSetUpdateManyWithWhereWithoutUserInput | Prisma.BiDataSetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BiDataSetScalarWhereInput | Prisma.BiDataSetScalarWhereInput[]
}

export type BiDataSetUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput> | Prisma.BiDataSetCreateWithoutUserInput[] | Prisma.BiDataSetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutUserInput | Prisma.BiDataSetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BiDataSetUpsertWithWhereUniqueWithoutUserInput | Prisma.BiDataSetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BiDataSetCreateManyUserInputEnvelope
  set?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  disconnect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  delete?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  connect?: Prisma.BiDataSetWhereUniqueInput | Prisma.BiDataSetWhereUniqueInput[]
  update?: Prisma.BiDataSetUpdateWithWhereUniqueWithoutUserInput | Prisma.BiDataSetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BiDataSetUpdateManyWithWhereWithoutUserInput | Prisma.BiDataSetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BiDataSetScalarWhereInput | Prisma.BiDataSetScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BiDataSetCreateNestedOneWithoutPanelsInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutPanelsInput, Prisma.BiDataSetUncheckedCreateWithoutPanelsInput>
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutPanelsInput
  connect?: Prisma.BiDataSetWhereUniqueInput
}

export type BiDataSetUpdateOneWithoutPanelsNestedInput = {
  create?: Prisma.XOR<Prisma.BiDataSetCreateWithoutPanelsInput, Prisma.BiDataSetUncheckedCreateWithoutPanelsInput>
  connectOrCreate?: Prisma.BiDataSetCreateOrConnectWithoutPanelsInput
  upsert?: Prisma.BiDataSetUpsertWithoutPanelsInput
  disconnect?: Prisma.BiDataSetWhereInput | boolean
  delete?: Prisma.BiDataSetWhereInput | boolean
  connect?: Prisma.BiDataSetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BiDataSetUpdateToOneWithWhereWithoutPanelsInput, Prisma.BiDataSetUpdateWithoutPanelsInput>, Prisma.BiDataSetUncheckedUpdateWithoutPanelsInput>
}

export type BiDataSetCreateWithoutUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  panels?: Prisma.BiPanelCreateNestedManyWithoutDataSetInput
}

export type BiDataSetUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  panels?: Prisma.BiPanelUncheckedCreateNestedManyWithoutDataSetInput
}

export type BiDataSetCreateOrConnectWithoutUserInput = {
  where: Prisma.BiDataSetWhereUniqueInput
  create: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput>
}

export type BiDataSetCreateManyUserInputEnvelope = {
  data: Prisma.BiDataSetCreateManyUserInput | Prisma.BiDataSetCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BiDataSetUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BiDataSetWhereUniqueInput
  update: Prisma.XOR<Prisma.BiDataSetUpdateWithoutUserInput, Prisma.BiDataSetUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BiDataSetCreateWithoutUserInput, Prisma.BiDataSetUncheckedCreateWithoutUserInput>
}

export type BiDataSetUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BiDataSetWhereUniqueInput
  data: Prisma.XOR<Prisma.BiDataSetUpdateWithoutUserInput, Prisma.BiDataSetUncheckedUpdateWithoutUserInput>
}

export type BiDataSetUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BiDataSetScalarWhereInput
  data: Prisma.XOR<Prisma.BiDataSetUpdateManyMutationInput, Prisma.BiDataSetUncheckedUpdateManyWithoutUserInput>
}

export type BiDataSetScalarWhereInput = {
  AND?: Prisma.BiDataSetScalarWhereInput | Prisma.BiDataSetScalarWhereInput[]
  OR?: Prisma.BiDataSetScalarWhereInput[]
  NOT?: Prisma.BiDataSetScalarWhereInput | Prisma.BiDataSetScalarWhereInput[]
  id?: Prisma.StringFilter<"BiDataSet"> | string
  name?: Prisma.StringFilter<"BiDataSet"> | string
  sql?: Prisma.StringFilter<"BiDataSet"> | string
  description?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataSet"> | boolean
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataSet"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataSet"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataSet"> | string | null
}

export type BiDataSetCreateWithoutPanelsInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutBiDataSetsInput
}

export type BiDataSetUncheckedCreateWithoutPanelsInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
}

export type BiDataSetCreateOrConnectWithoutPanelsInput = {
  where: Prisma.BiDataSetWhereUniqueInput
  create: Prisma.XOR<Prisma.BiDataSetCreateWithoutPanelsInput, Prisma.BiDataSetUncheckedCreateWithoutPanelsInput>
}

export type BiDataSetUpsertWithoutPanelsInput = {
  update: Prisma.XOR<Prisma.BiDataSetUpdateWithoutPanelsInput, Prisma.BiDataSetUncheckedUpdateWithoutPanelsInput>
  create: Prisma.XOR<Prisma.BiDataSetCreateWithoutPanelsInput, Prisma.BiDataSetUncheckedCreateWithoutPanelsInput>
  where?: Prisma.BiDataSetWhereInput
}

export type BiDataSetUpdateToOneWithWhereWithoutPanelsInput = {
  where?: Prisma.BiDataSetWhereInput
  data: Prisma.XOR<Prisma.BiDataSetUpdateWithoutPanelsInput, Prisma.BiDataSetUncheckedUpdateWithoutPanelsInput>
}

export type BiDataSetUpdateWithoutPanelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutBiDataSetsNestedInput
}

export type BiDataSetUncheckedUpdateWithoutPanelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BiDataSetCreateManyUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiDataSetUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  panels?: Prisma.BiPanelUpdateManyWithoutDataSetNestedInput
}

export type BiDataSetUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  panels?: Prisma.BiPanelUncheckedUpdateManyWithoutDataSetNestedInput
}

export type BiDataSetUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BiDataSetCountOutputType
 */

export type BiDataSetCountOutputType = {
  panels: number
}

export type BiDataSetCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  panels?: boolean | BiDataSetCountOutputTypeCountPanelsArgs
}

/**
 * BiDataSetCountOutputType without action
 */
export type BiDataSetCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSetCountOutputType
   */
  select?: Prisma.BiDataSetCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BiDataSetCountOutputType without action
 */
export type BiDataSetCountOutputTypeCountPanelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiPanelWhereInput
}


export type BiDataSetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  panels?: boolean | Prisma.BiDataSet$panelsArgs<ExtArgs>
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
  _count?: boolean | Prisma.BiDataSetCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biDataSet"]>

export type BiDataSetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
}, ExtArgs["result"]["biDataSet"]>

export type BiDataSetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
}, ExtArgs["result"]["biDataSet"]>

export type BiDataSetSelectScalar = {
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
}

export type BiDataSetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "sql" | "description" | "isPublic" | "lastRunAt" | "createdAt" | "updatedAt" | "userId", ExtArgs["result"]["biDataSet"]>
export type BiDataSetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  panels?: boolean | Prisma.BiDataSet$panelsArgs<ExtArgs>
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
  _count?: boolean | Prisma.BiDataSetCountOutputTypeDefaultArgs<ExtArgs>
}
export type BiDataSetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
}
export type BiDataSetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.BiDataSet$userArgs<ExtArgs>
}

export type $BiDataSetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BiDataSet"
  objects: {
    panels: Prisma.$BiPanelPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    sql: string
    description: string | null
    isPublic: boolean
    lastRunAt: Date | null
    createdAt: Date
    updatedAt: Date
    userId: string | null
  }, ExtArgs["result"]["biDataSet"]>
  composites: {}
}

export type BiDataSetGetPayload<S extends boolean | null | undefined | BiDataSetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload, S>

export type BiDataSetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BiDataSetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BiDataSetCountAggregateInputType | true
  }

export interface BiDataSetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BiDataSet'], meta: { name: 'BiDataSet' } }
  /**
   * Find zero or one BiDataSet that matches the filter.
   * @param {BiDataSetFindUniqueArgs} args - Arguments to find a BiDataSet
   * @example
   * // Get one BiDataSet
   * const biDataSet = await prisma.biDataSet.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BiDataSetFindUniqueArgs>(args: Prisma.SelectSubset<T, BiDataSetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BiDataSet that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BiDataSetFindUniqueOrThrowArgs} args - Arguments to find a BiDataSet
   * @example
   * // Get one BiDataSet
   * const biDataSet = await prisma.biDataSet.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BiDataSetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BiDataSetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiDataSet that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetFindFirstArgs} args - Arguments to find a BiDataSet
   * @example
   * // Get one BiDataSet
   * const biDataSet = await prisma.biDataSet.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BiDataSetFindFirstArgs>(args?: Prisma.SelectSubset<T, BiDataSetFindFirstArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiDataSet that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetFindFirstOrThrowArgs} args - Arguments to find a BiDataSet
   * @example
   * // Get one BiDataSet
   * const biDataSet = await prisma.biDataSet.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BiDataSetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BiDataSetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BiDataSets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BiDataSets
   * const biDataSets = await prisma.biDataSet.findMany()
   * 
   * // Get first 10 BiDataSets
   * const biDataSets = await prisma.biDataSet.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const biDataSetWithIdOnly = await prisma.biDataSet.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BiDataSetFindManyArgs>(args?: Prisma.SelectSubset<T, BiDataSetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BiDataSet.
   * @param {BiDataSetCreateArgs} args - Arguments to create a BiDataSet.
   * @example
   * // Create one BiDataSet
   * const BiDataSet = await prisma.biDataSet.create({
   *   data: {
   *     // ... data to create a BiDataSet
   *   }
   * })
   * 
   */
  create<T extends BiDataSetCreateArgs>(args: Prisma.SelectSubset<T, BiDataSetCreateArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BiDataSets.
   * @param {BiDataSetCreateManyArgs} args - Arguments to create many BiDataSets.
   * @example
   * // Create many BiDataSets
   * const biDataSet = await prisma.biDataSet.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BiDataSetCreateManyArgs>(args?: Prisma.SelectSubset<T, BiDataSetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BiDataSets and returns the data saved in the database.
   * @param {BiDataSetCreateManyAndReturnArgs} args - Arguments to create many BiDataSets.
   * @example
   * // Create many BiDataSets
   * const biDataSet = await prisma.biDataSet.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BiDataSets and only return the `id`
   * const biDataSetWithIdOnly = await prisma.biDataSet.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BiDataSetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BiDataSetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BiDataSet.
   * @param {BiDataSetDeleteArgs} args - Arguments to delete one BiDataSet.
   * @example
   * // Delete one BiDataSet
   * const BiDataSet = await prisma.biDataSet.delete({
   *   where: {
   *     // ... filter to delete one BiDataSet
   *   }
   * })
   * 
   */
  delete<T extends BiDataSetDeleteArgs>(args: Prisma.SelectSubset<T, BiDataSetDeleteArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BiDataSet.
   * @param {BiDataSetUpdateArgs} args - Arguments to update one BiDataSet.
   * @example
   * // Update one BiDataSet
   * const biDataSet = await prisma.biDataSet.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BiDataSetUpdateArgs>(args: Prisma.SelectSubset<T, BiDataSetUpdateArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BiDataSets.
   * @param {BiDataSetDeleteManyArgs} args - Arguments to filter BiDataSets to delete.
   * @example
   * // Delete a few BiDataSets
   * const { count } = await prisma.biDataSet.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BiDataSetDeleteManyArgs>(args?: Prisma.SelectSubset<T, BiDataSetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiDataSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BiDataSets
   * const biDataSet = await prisma.biDataSet.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BiDataSetUpdateManyArgs>(args: Prisma.SelectSubset<T, BiDataSetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiDataSets and returns the data updated in the database.
   * @param {BiDataSetUpdateManyAndReturnArgs} args - Arguments to update many BiDataSets.
   * @example
   * // Update many BiDataSets
   * const biDataSet = await prisma.biDataSet.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BiDataSets and only return the `id`
   * const biDataSetWithIdOnly = await prisma.biDataSet.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BiDataSetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BiDataSetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BiDataSet.
   * @param {BiDataSetUpsertArgs} args - Arguments to update or create a BiDataSet.
   * @example
   * // Update or create a BiDataSet
   * const biDataSet = await prisma.biDataSet.upsert({
   *   create: {
   *     // ... data to create a BiDataSet
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BiDataSet we want to update
   *   }
   * })
   */
  upsert<T extends BiDataSetUpsertArgs>(args: Prisma.SelectSubset<T, BiDataSetUpsertArgs<ExtArgs>>): Prisma.Prisma__BiDataSetClient<runtime.Types.Result.GetResult<Prisma.$BiDataSetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BiDataSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetCountArgs} args - Arguments to filter BiDataSets to count.
   * @example
   * // Count the number of BiDataSets
   * const count = await prisma.biDataSet.count({
   *   where: {
   *     // ... the filter for the BiDataSets we want to count
   *   }
   * })
  **/
  count<T extends BiDataSetCountArgs>(
    args?: Prisma.Subset<T, BiDataSetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BiDataSetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BiDataSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BiDataSetAggregateArgs>(args: Prisma.Subset<T, BiDataSetAggregateArgs>): Prisma.PrismaPromise<GetBiDataSetAggregateType<T>>

  /**
   * Group by BiDataSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDataSetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BiDataSetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BiDataSetGroupByArgs['orderBy'] }
      : { orderBy?: BiDataSetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BiDataSetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBiDataSetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BiDataSet model
 */
readonly fields: BiDataSetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BiDataSet.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BiDataSetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  panels<T extends Prisma.BiDataSet$panelsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDataSet$panelsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.BiDataSet$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDataSet$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BiDataSet model
 */
export interface BiDataSetFieldRefs {
  readonly id: Prisma.FieldRef<"BiDataSet", 'String'>
  readonly name: Prisma.FieldRef<"BiDataSet", 'String'>
  readonly sql: Prisma.FieldRef<"BiDataSet", 'String'>
  readonly description: Prisma.FieldRef<"BiDataSet", 'String'>
  readonly isPublic: Prisma.FieldRef<"BiDataSet", 'Boolean'>
  readonly lastRunAt: Prisma.FieldRef<"BiDataSet", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"BiDataSet", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BiDataSet", 'DateTime'>
  readonly userId: Prisma.FieldRef<"BiDataSet", 'String'>
}
    

// Custom InputTypes
/**
 * BiDataSet findUnique
 */
export type BiDataSetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataSet to fetch.
   */
  where: Prisma.BiDataSetWhereUniqueInput
}

/**
 * BiDataSet findUniqueOrThrow
 */
export type BiDataSetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataSet to fetch.
   */
  where: Prisma.BiDataSetWhereUniqueInput
}

/**
 * BiDataSet findFirst
 */
export type BiDataSetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataSet to fetch.
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDataSets to fetch.
   */
  orderBy?: Prisma.BiDataSetOrderByWithRelationInput | Prisma.BiDataSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiDataSets.
   */
  cursor?: Prisma.BiDataSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDataSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDataSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDataSets.
   */
  distinct?: Prisma.BiDataSetScalarFieldEnum | Prisma.BiDataSetScalarFieldEnum[]
}

/**
 * BiDataSet findFirstOrThrow
 */
export type BiDataSetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataSet to fetch.
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDataSets to fetch.
   */
  orderBy?: Prisma.BiDataSetOrderByWithRelationInput | Prisma.BiDataSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiDataSets.
   */
  cursor?: Prisma.BiDataSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDataSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDataSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDataSets.
   */
  distinct?: Prisma.BiDataSetScalarFieldEnum | Prisma.BiDataSetScalarFieldEnum[]
}

/**
 * BiDataSet findMany
 */
export type BiDataSetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataSets to fetch.
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDataSets to fetch.
   */
  orderBy?: Prisma.BiDataSetOrderByWithRelationInput | Prisma.BiDataSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BiDataSets.
   */
  cursor?: Prisma.BiDataSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDataSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDataSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDataSets.
   */
  distinct?: Prisma.BiDataSetScalarFieldEnum | Prisma.BiDataSetScalarFieldEnum[]
}

/**
 * BiDataSet create
 */
export type BiDataSetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * The data needed to create a BiDataSet.
   */
  data: Prisma.XOR<Prisma.BiDataSetCreateInput, Prisma.BiDataSetUncheckedCreateInput>
}

/**
 * BiDataSet createMany
 */
export type BiDataSetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BiDataSets.
   */
  data: Prisma.BiDataSetCreateManyInput | Prisma.BiDataSetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BiDataSet createManyAndReturn
 */
export type BiDataSetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * The data used to create many BiDataSets.
   */
  data: Prisma.BiDataSetCreateManyInput | Prisma.BiDataSetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BiDataSet update
 */
export type BiDataSetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * The data needed to update a BiDataSet.
   */
  data: Prisma.XOR<Prisma.BiDataSetUpdateInput, Prisma.BiDataSetUncheckedUpdateInput>
  /**
   * Choose, which BiDataSet to update.
   */
  where: Prisma.BiDataSetWhereUniqueInput
}

/**
 * BiDataSet updateMany
 */
export type BiDataSetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BiDataSets.
   */
  data: Prisma.XOR<Prisma.BiDataSetUpdateManyMutationInput, Prisma.BiDataSetUncheckedUpdateManyInput>
  /**
   * Filter which BiDataSets to update
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * Limit how many BiDataSets to update.
   */
  limit?: number
}

/**
 * BiDataSet updateManyAndReturn
 */
export type BiDataSetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * The data used to update BiDataSets.
   */
  data: Prisma.XOR<Prisma.BiDataSetUpdateManyMutationInput, Prisma.BiDataSetUncheckedUpdateManyInput>
  /**
   * Filter which BiDataSets to update
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * Limit how many BiDataSets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BiDataSet upsert
 */
export type BiDataSetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * The filter to search for the BiDataSet to update in case it exists.
   */
  where: Prisma.BiDataSetWhereUniqueInput
  /**
   * In case the BiDataSet found by the `where` argument doesn't exist, create a new BiDataSet with this data.
   */
  create: Prisma.XOR<Prisma.BiDataSetCreateInput, Prisma.BiDataSetUncheckedCreateInput>
  /**
   * In case the BiDataSet was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BiDataSetUpdateInput, Prisma.BiDataSetUncheckedUpdateInput>
}

/**
 * BiDataSet delete
 */
export type BiDataSetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
  /**
   * Filter which BiDataSet to delete.
   */
  where: Prisma.BiDataSetWhereUniqueInput
}

/**
 * BiDataSet deleteMany
 */
export type BiDataSetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiDataSets to delete
   */
  where?: Prisma.BiDataSetWhereInput
  /**
   * Limit how many BiDataSets to delete.
   */
  limit?: number
}

/**
 * BiDataSet.panels
 */
export type BiDataSet$panelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  where?: Prisma.BiPanelWhereInput
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  cursor?: Prisma.BiPanelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiPanelScalarFieldEnum | Prisma.BiPanelScalarFieldEnum[]
}

/**
 * BiDataSet.user
 */
export type BiDataSet$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * BiDataSet without action
 */
export type BiDataSetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataSet
   */
  select?: Prisma.BiDataSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataSet
   */
  omit?: Prisma.BiDataSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDataSetInclude<ExtArgs> | null
}
