
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BiDataset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BiDataset
 * 
 */
export type BiDatasetModel = runtime.Types.Result.DefaultSelection<Prisma.$BiDatasetPayload>

export type AggregateBiDataset = {
  _count: BiDatasetCountAggregateOutputType | null
  _min: BiDatasetMinAggregateOutputType | null
  _max: BiDatasetMaxAggregateOutputType | null
}

export type BiDatasetMinAggregateOutputType = {
  id: string | null
  name: string | null
  sql: string | null
  description: string | null
  isPublic: boolean | null
  sourceId: string | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type BiDatasetMaxAggregateOutputType = {
  id: string | null
  name: string | null
  sql: string | null
  description: string | null
  isPublic: boolean | null
  sourceId: string | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type BiDatasetCountAggregateOutputType = {
  id: number
  name: number
  sql: number
  description: number
  isPublic: number
  sourceId: number
  lastRunAt: number
  createdAt: number
  updatedAt: number
  userId: number
  _all: number
}


export type BiDatasetMinAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  sourceId?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type BiDatasetMaxAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  sourceId?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type BiDatasetCountAggregateInputType = {
  id?: true
  name?: true
  sql?: true
  description?: true
  isPublic?: true
  sourceId?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  _all?: true
}

export type BiDatasetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiDataset to aggregate.
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDatasets to fetch.
   */
  orderBy?: Prisma.BiDatasetOrderByWithRelationInput | Prisma.BiDatasetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BiDatasetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDatasets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDatasets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BiDatasets
  **/
  _count?: true | BiDatasetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BiDatasetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BiDatasetMaxAggregateInputType
}

export type GetBiDatasetAggregateType<T extends BiDatasetAggregateArgs> = {
      [P in keyof T & keyof AggregateBiDataset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBiDataset[P]>
    : Prisma.GetScalarType<T[P], AggregateBiDataset[P]>
}




export type BiDatasetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDatasetWhereInput
  orderBy?: Prisma.BiDatasetOrderByWithAggregationInput | Prisma.BiDatasetOrderByWithAggregationInput[]
  by: Prisma.BiDatasetScalarFieldEnum[] | Prisma.BiDatasetScalarFieldEnum
  having?: Prisma.BiDatasetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BiDatasetCountAggregateInputType | true
  _min?: BiDatasetMinAggregateInputType
  _max?: BiDatasetMaxAggregateInputType
}

export type BiDatasetGroupByOutputType = {
  id: string
  name: string
  sql: string
  description: string | null
  isPublic: boolean
  sourceId: string | null
  lastRunAt: Date | null
  createdAt: Date
  updatedAt: Date
  userId: string | null
  _count: BiDatasetCountAggregateOutputType | null
  _min: BiDatasetMinAggregateOutputType | null
  _max: BiDatasetMaxAggregateOutputType | null
}

export type GetBiDatasetGroupByPayload<T extends BiDatasetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BiDatasetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BiDatasetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BiDatasetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BiDatasetGroupByOutputType[P]>
      }
    >
  >



export type BiDatasetWhereInput = {
  AND?: Prisma.BiDatasetWhereInput | Prisma.BiDatasetWhereInput[]
  OR?: Prisma.BiDatasetWhereInput[]
  NOT?: Prisma.BiDatasetWhereInput | Prisma.BiDatasetWhereInput[]
  id?: Prisma.StringFilter<"BiDataset"> | string
  name?: Prisma.StringFilter<"BiDataset"> | string
  sql?: Prisma.StringFilter<"BiDataset"> | string
  description?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataset"> | boolean
  sourceId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataset"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  source?: Prisma.XOR<Prisma.BiSourceNullableScalarRelationFilter, Prisma.BiSourceWhereInput> | null
  panels?: Prisma.BiPanelListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type BiDatasetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  sourceId?: Prisma.SortOrderInput | Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.BiSourceOrderByWithRelationInput
  panels?: Prisma.BiPanelOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type BiDatasetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BiDatasetWhereInput | Prisma.BiDatasetWhereInput[]
  OR?: Prisma.BiDatasetWhereInput[]
  NOT?: Prisma.BiDatasetWhereInput | Prisma.BiDatasetWhereInput[]
  name?: Prisma.StringFilter<"BiDataset"> | string
  sql?: Prisma.StringFilter<"BiDataset"> | string
  description?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataset"> | boolean
  sourceId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataset"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  source?: Prisma.XOR<Prisma.BiSourceNullableScalarRelationFilter, Prisma.BiSourceWhereInput> | null
  panels?: Prisma.BiPanelListRelationFilter
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type BiDatasetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  sourceId?: Prisma.SortOrderInput | Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BiDatasetCountOrderByAggregateInput
  _max?: Prisma.BiDatasetMaxOrderByAggregateInput
  _min?: Prisma.BiDatasetMinOrderByAggregateInput
}

export type BiDatasetScalarWhereWithAggregatesInput = {
  AND?: Prisma.BiDatasetScalarWhereWithAggregatesInput | Prisma.BiDatasetScalarWhereWithAggregatesInput[]
  OR?: Prisma.BiDatasetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BiDatasetScalarWhereWithAggregatesInput | Prisma.BiDatasetScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BiDataset"> | string
  name?: Prisma.StringWithAggregatesFilter<"BiDataset"> | string
  sql?: Prisma.StringWithAggregatesFilter<"BiDataset"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"BiDataset"> | string | null
  isPublic?: Prisma.BoolWithAggregatesFilter<"BiDataset"> | boolean
  sourceId?: Prisma.StringNullableWithAggregatesFilter<"BiDataset"> | string | null
  lastRunAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BiDataset"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BiDataset"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BiDataset"> | Date | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"BiDataset"> | string | null
}

export type BiDatasetCreateInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  source?: Prisma.BiSourceCreateNestedOneWithoutDatasetsInput
  panels?: Prisma.BiPanelCreateNestedManyWithoutDataSetInput
  user?: Prisma.UserCreateNestedOneWithoutBiDatasetsInput
}

export type BiDatasetUncheckedCreateInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  sourceId?: string | null
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
  panels?: Prisma.BiPanelUncheckedCreateNestedManyWithoutDataSetInput
}

export type BiDatasetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.BiSourceUpdateOneWithoutDatasetsNestedInput
  panels?: Prisma.BiPanelUpdateManyWithoutDataSetNestedInput
  user?: Prisma.UserUpdateOneWithoutBiDatasetsNestedInput
}

export type BiDatasetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sourceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  panels?: Prisma.BiPanelUncheckedUpdateManyWithoutDataSetNestedInput
}

export type BiDatasetCreateManyInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  sourceId?: string | null
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
}

export type BiDatasetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiDatasetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sourceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BiDatasetListRelationFilter = {
  every?: Prisma.BiDatasetWhereInput
  some?: Prisma.BiDatasetWhereInput
  none?: Prisma.BiDatasetWhereInput
}

export type BiDatasetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BiDatasetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDatasetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDatasetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sql?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BiDatasetNullableScalarRelationFilter = {
  is?: Prisma.BiDatasetWhereInput | null
  isNot?: Prisma.BiDatasetWhereInput | null
}

export type BiDatasetCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput> | Prisma.BiDatasetCreateWithoutUserInput[] | Prisma.BiDatasetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutUserInput | Prisma.BiDatasetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BiDatasetCreateManyUserInputEnvelope
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
}

export type BiDatasetUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput> | Prisma.BiDatasetCreateWithoutUserInput[] | Prisma.BiDatasetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutUserInput | Prisma.BiDatasetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BiDatasetCreateManyUserInputEnvelope
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
}

export type BiDatasetUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput> | Prisma.BiDatasetCreateWithoutUserInput[] | Prisma.BiDatasetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutUserInput | Prisma.BiDatasetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BiDatasetUpsertWithWhereUniqueWithoutUserInput | Prisma.BiDatasetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BiDatasetCreateManyUserInputEnvelope
  set?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  disconnect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  delete?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  update?: Prisma.BiDatasetUpdateWithWhereUniqueWithoutUserInput | Prisma.BiDatasetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BiDatasetUpdateManyWithWhereWithoutUserInput | Prisma.BiDatasetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
}

export type BiDatasetUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput> | Prisma.BiDatasetCreateWithoutUserInput[] | Prisma.BiDatasetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutUserInput | Prisma.BiDatasetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BiDatasetUpsertWithWhereUniqueWithoutUserInput | Prisma.BiDatasetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BiDatasetCreateManyUserInputEnvelope
  set?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  disconnect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  delete?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  update?: Prisma.BiDatasetUpdateWithWhereUniqueWithoutUserInput | Prisma.BiDatasetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BiDatasetUpdateManyWithWhereWithoutUserInput | Prisma.BiDatasetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BiDatasetCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput> | Prisma.BiDatasetCreateWithoutSourceInput[] | Prisma.BiDatasetUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutSourceInput | Prisma.BiDatasetCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.BiDatasetCreateManySourceInputEnvelope
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
}

export type BiDatasetUncheckedCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput> | Prisma.BiDatasetCreateWithoutSourceInput[] | Prisma.BiDatasetUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutSourceInput | Prisma.BiDatasetCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.BiDatasetCreateManySourceInputEnvelope
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
}

export type BiDatasetUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput> | Prisma.BiDatasetCreateWithoutSourceInput[] | Prisma.BiDatasetUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutSourceInput | Prisma.BiDatasetCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.BiDatasetUpsertWithWhereUniqueWithoutSourceInput | Prisma.BiDatasetUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.BiDatasetCreateManySourceInputEnvelope
  set?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  disconnect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  delete?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  update?: Prisma.BiDatasetUpdateWithWhereUniqueWithoutSourceInput | Prisma.BiDatasetUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.BiDatasetUpdateManyWithWhereWithoutSourceInput | Prisma.BiDatasetUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
}

export type BiDatasetUncheckedUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput> | Prisma.BiDatasetCreateWithoutSourceInput[] | Prisma.BiDatasetUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutSourceInput | Prisma.BiDatasetCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.BiDatasetUpsertWithWhereUniqueWithoutSourceInput | Prisma.BiDatasetUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.BiDatasetCreateManySourceInputEnvelope
  set?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  disconnect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  delete?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  connect?: Prisma.BiDatasetWhereUniqueInput | Prisma.BiDatasetWhereUniqueInput[]
  update?: Prisma.BiDatasetUpdateWithWhereUniqueWithoutSourceInput | Prisma.BiDatasetUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.BiDatasetUpdateManyWithWhereWithoutSourceInput | Prisma.BiDatasetUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
}

export type BiDatasetCreateNestedOneWithoutPanelsInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutPanelsInput, Prisma.BiDatasetUncheckedCreateWithoutPanelsInput>
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutPanelsInput
  connect?: Prisma.BiDatasetWhereUniqueInput
}

export type BiDatasetUpdateOneWithoutPanelsNestedInput = {
  create?: Prisma.XOR<Prisma.BiDatasetCreateWithoutPanelsInput, Prisma.BiDatasetUncheckedCreateWithoutPanelsInput>
  connectOrCreate?: Prisma.BiDatasetCreateOrConnectWithoutPanelsInput
  upsert?: Prisma.BiDatasetUpsertWithoutPanelsInput
  disconnect?: Prisma.BiDatasetWhereInput | boolean
  delete?: Prisma.BiDatasetWhereInput | boolean
  connect?: Prisma.BiDatasetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BiDatasetUpdateToOneWithWhereWithoutPanelsInput, Prisma.BiDatasetUpdateWithoutPanelsInput>, Prisma.BiDatasetUncheckedUpdateWithoutPanelsInput>
}

export type BiDatasetCreateWithoutUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  source?: Prisma.BiSourceCreateNestedOneWithoutDatasetsInput
  panels?: Prisma.BiPanelCreateNestedManyWithoutDataSetInput
}

export type BiDatasetUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  sourceId?: string | null
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  panels?: Prisma.BiPanelUncheckedCreateNestedManyWithoutDataSetInput
}

export type BiDatasetCreateOrConnectWithoutUserInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput>
}

export type BiDatasetCreateManyUserInputEnvelope = {
  data: Prisma.BiDatasetCreateManyUserInput | Prisma.BiDatasetCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BiDatasetUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  update: Prisma.XOR<Prisma.BiDatasetUpdateWithoutUserInput, Prisma.BiDatasetUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutUserInput, Prisma.BiDatasetUncheckedCreateWithoutUserInput>
}

export type BiDatasetUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  data: Prisma.XOR<Prisma.BiDatasetUpdateWithoutUserInput, Prisma.BiDatasetUncheckedUpdateWithoutUserInput>
}

export type BiDatasetUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BiDatasetScalarWhereInput
  data: Prisma.XOR<Prisma.BiDatasetUpdateManyMutationInput, Prisma.BiDatasetUncheckedUpdateManyWithoutUserInput>
}

export type BiDatasetScalarWhereInput = {
  AND?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
  OR?: Prisma.BiDatasetScalarWhereInput[]
  NOT?: Prisma.BiDatasetScalarWhereInput | Prisma.BiDatasetScalarWhereInput[]
  id?: Prisma.StringFilter<"BiDataset"> | string
  name?: Prisma.StringFilter<"BiDataset"> | string
  sql?: Prisma.StringFilter<"BiDataset"> | string
  description?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  isPublic?: Prisma.BoolFilter<"BiDataset"> | boolean
  sourceId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
  lastRunAt?: Prisma.DateTimeNullableFilter<"BiDataset"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiDataset"> | Date | string
  userId?: Prisma.StringNullableFilter<"BiDataset"> | string | null
}

export type BiDatasetCreateWithoutSourceInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  panels?: Prisma.BiPanelCreateNestedManyWithoutDataSetInput
  user?: Prisma.UserCreateNestedOneWithoutBiDatasetsInput
}

export type BiDatasetUncheckedCreateWithoutSourceInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
  panels?: Prisma.BiPanelUncheckedCreateNestedManyWithoutDataSetInput
}

export type BiDatasetCreateOrConnectWithoutSourceInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput>
}

export type BiDatasetCreateManySourceInputEnvelope = {
  data: Prisma.BiDatasetCreateManySourceInput | Prisma.BiDatasetCreateManySourceInput[]
  skipDuplicates?: boolean
}

export type BiDatasetUpsertWithWhereUniqueWithoutSourceInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  update: Prisma.XOR<Prisma.BiDatasetUpdateWithoutSourceInput, Prisma.BiDatasetUncheckedUpdateWithoutSourceInput>
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutSourceInput, Prisma.BiDatasetUncheckedCreateWithoutSourceInput>
}

export type BiDatasetUpdateWithWhereUniqueWithoutSourceInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  data: Prisma.XOR<Prisma.BiDatasetUpdateWithoutSourceInput, Prisma.BiDatasetUncheckedUpdateWithoutSourceInput>
}

export type BiDatasetUpdateManyWithWhereWithoutSourceInput = {
  where: Prisma.BiDatasetScalarWhereInput
  data: Prisma.XOR<Prisma.BiDatasetUpdateManyMutationInput, Prisma.BiDatasetUncheckedUpdateManyWithoutSourceInput>
}

export type BiDatasetCreateWithoutPanelsInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  source?: Prisma.BiSourceCreateNestedOneWithoutDatasetsInput
  user?: Prisma.UserCreateNestedOneWithoutBiDatasetsInput
}

export type BiDatasetUncheckedCreateWithoutPanelsInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  sourceId?: string | null
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
}

export type BiDatasetCreateOrConnectWithoutPanelsInput = {
  where: Prisma.BiDatasetWhereUniqueInput
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutPanelsInput, Prisma.BiDatasetUncheckedCreateWithoutPanelsInput>
}

export type BiDatasetUpsertWithoutPanelsInput = {
  update: Prisma.XOR<Prisma.BiDatasetUpdateWithoutPanelsInput, Prisma.BiDatasetUncheckedUpdateWithoutPanelsInput>
  create: Prisma.XOR<Prisma.BiDatasetCreateWithoutPanelsInput, Prisma.BiDatasetUncheckedCreateWithoutPanelsInput>
  where?: Prisma.BiDatasetWhereInput
}

export type BiDatasetUpdateToOneWithWhereWithoutPanelsInput = {
  where?: Prisma.BiDatasetWhereInput
  data: Prisma.XOR<Prisma.BiDatasetUpdateWithoutPanelsInput, Prisma.BiDatasetUncheckedUpdateWithoutPanelsInput>
}

export type BiDatasetUpdateWithoutPanelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.BiSourceUpdateOneWithoutDatasetsNestedInput
  user?: Prisma.UserUpdateOneWithoutBiDatasetsNestedInput
}

export type BiDatasetUncheckedUpdateWithoutPanelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sourceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BiDatasetCreateManyUserInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  sourceId?: string | null
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiDatasetUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.BiSourceUpdateOneWithoutDatasetsNestedInput
  panels?: Prisma.BiPanelUpdateManyWithoutDataSetNestedInput
}

export type BiDatasetUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sourceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  panels?: Prisma.BiPanelUncheckedUpdateManyWithoutDataSetNestedInput
}

export type BiDatasetUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sourceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiDatasetCreateManySourceInput = {
  id?: string
  name: string
  sql: string
  description?: string | null
  isPublic?: boolean
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
}

export type BiDatasetUpdateWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  panels?: Prisma.BiPanelUpdateManyWithoutDataSetNestedInput
  user?: Prisma.UserUpdateOneWithoutBiDatasetsNestedInput
}

export type BiDatasetUncheckedUpdateWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  panels?: Prisma.BiPanelUncheckedUpdateManyWithoutDataSetNestedInput
}

export type BiDatasetUncheckedUpdateManyWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sql?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type BiDatasetCountOutputType
 */

export type BiDatasetCountOutputType = {
  panels: number
}

export type BiDatasetCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  panels?: boolean | BiDatasetCountOutputTypeCountPanelsArgs
}

/**
 * BiDatasetCountOutputType without action
 */
export type BiDatasetCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDatasetCountOutputType
   */
  select?: Prisma.BiDatasetCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BiDatasetCountOutputType without action
 */
export type BiDatasetCountOutputTypeCountPanelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiPanelWhereInput
}


export type BiDatasetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  sourceId?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  panels?: boolean | Prisma.BiDataset$panelsArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
  _count?: boolean | Prisma.BiDatasetCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biDataset"]>

export type BiDatasetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  sourceId?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
}, ExtArgs["result"]["biDataset"]>

export type BiDatasetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  sourceId?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
}, ExtArgs["result"]["biDataset"]>

export type BiDatasetSelectScalar = {
  id?: boolean
  name?: boolean
  sql?: boolean
  description?: boolean
  isPublic?: boolean
  sourceId?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
}

export type BiDatasetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "sql" | "description" | "isPublic" | "sourceId" | "lastRunAt" | "createdAt" | "updatedAt" | "userId", ExtArgs["result"]["biDataset"]>
export type BiDatasetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  panels?: boolean | Prisma.BiDataset$panelsArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
  _count?: boolean | Prisma.BiDatasetCountOutputTypeDefaultArgs<ExtArgs>
}
export type BiDatasetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
}
export type BiDatasetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.BiDataset$sourceArgs<ExtArgs>
  user?: boolean | Prisma.BiDataset$userArgs<ExtArgs>
}

export type $BiDatasetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BiDataset"
  objects: {
    source: Prisma.$BiSourcePayload<ExtArgs> | null
    panels: Prisma.$BiPanelPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    sql: string
    description: string | null
    isPublic: boolean
    sourceId: string | null
    lastRunAt: Date | null
    createdAt: Date
    updatedAt: Date
    userId: string | null
  }, ExtArgs["result"]["biDataset"]>
  composites: {}
}

export type BiDatasetGetPayload<S extends boolean | null | undefined | BiDatasetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload, S>

export type BiDatasetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BiDatasetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BiDatasetCountAggregateInputType | true
  }

export interface BiDatasetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BiDataset'], meta: { name: 'BiDataset' } }
  /**
   * Find zero or one BiDataset that matches the filter.
   * @param {BiDatasetFindUniqueArgs} args - Arguments to find a BiDataset
   * @example
   * // Get one BiDataset
   * const biDataset = await prisma.biDataset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BiDatasetFindUniqueArgs>(args: Prisma.SelectSubset<T, BiDatasetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BiDataset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BiDatasetFindUniqueOrThrowArgs} args - Arguments to find a BiDataset
   * @example
   * // Get one BiDataset
   * const biDataset = await prisma.biDataset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BiDatasetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BiDatasetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiDataset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetFindFirstArgs} args - Arguments to find a BiDataset
   * @example
   * // Get one BiDataset
   * const biDataset = await prisma.biDataset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BiDatasetFindFirstArgs>(args?: Prisma.SelectSubset<T, BiDatasetFindFirstArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiDataset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetFindFirstOrThrowArgs} args - Arguments to find a BiDataset
   * @example
   * // Get one BiDataset
   * const biDataset = await prisma.biDataset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BiDatasetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BiDatasetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BiDatasets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BiDatasets
   * const biDatasets = await prisma.biDataset.findMany()
   * 
   * // Get first 10 BiDatasets
   * const biDatasets = await prisma.biDataset.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const biDatasetWithIdOnly = await prisma.biDataset.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BiDatasetFindManyArgs>(args?: Prisma.SelectSubset<T, BiDatasetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BiDataset.
   * @param {BiDatasetCreateArgs} args - Arguments to create a BiDataset.
   * @example
   * // Create one BiDataset
   * const BiDataset = await prisma.biDataset.create({
   *   data: {
   *     // ... data to create a BiDataset
   *   }
   * })
   * 
   */
  create<T extends BiDatasetCreateArgs>(args: Prisma.SelectSubset<T, BiDatasetCreateArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BiDatasets.
   * @param {BiDatasetCreateManyArgs} args - Arguments to create many BiDatasets.
   * @example
   * // Create many BiDatasets
   * const biDataset = await prisma.biDataset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BiDatasetCreateManyArgs>(args?: Prisma.SelectSubset<T, BiDatasetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BiDatasets and returns the data saved in the database.
   * @param {BiDatasetCreateManyAndReturnArgs} args - Arguments to create many BiDatasets.
   * @example
   * // Create many BiDatasets
   * const biDataset = await prisma.biDataset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BiDatasets and only return the `id`
   * const biDatasetWithIdOnly = await prisma.biDataset.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BiDatasetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BiDatasetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BiDataset.
   * @param {BiDatasetDeleteArgs} args - Arguments to delete one BiDataset.
   * @example
   * // Delete one BiDataset
   * const BiDataset = await prisma.biDataset.delete({
   *   where: {
   *     // ... filter to delete one BiDataset
   *   }
   * })
   * 
   */
  delete<T extends BiDatasetDeleteArgs>(args: Prisma.SelectSubset<T, BiDatasetDeleteArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BiDataset.
   * @param {BiDatasetUpdateArgs} args - Arguments to update one BiDataset.
   * @example
   * // Update one BiDataset
   * const biDataset = await prisma.biDataset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BiDatasetUpdateArgs>(args: Prisma.SelectSubset<T, BiDatasetUpdateArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BiDatasets.
   * @param {BiDatasetDeleteManyArgs} args - Arguments to filter BiDatasets to delete.
   * @example
   * // Delete a few BiDatasets
   * const { count } = await prisma.biDataset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BiDatasetDeleteManyArgs>(args?: Prisma.SelectSubset<T, BiDatasetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiDatasets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BiDatasets
   * const biDataset = await prisma.biDataset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BiDatasetUpdateManyArgs>(args: Prisma.SelectSubset<T, BiDatasetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiDatasets and returns the data updated in the database.
   * @param {BiDatasetUpdateManyAndReturnArgs} args - Arguments to update many BiDatasets.
   * @example
   * // Update many BiDatasets
   * const biDataset = await prisma.biDataset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BiDatasets and only return the `id`
   * const biDatasetWithIdOnly = await prisma.biDataset.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BiDatasetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BiDatasetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BiDataset.
   * @param {BiDatasetUpsertArgs} args - Arguments to update or create a BiDataset.
   * @example
   * // Update or create a BiDataset
   * const biDataset = await prisma.biDataset.upsert({
   *   create: {
   *     // ... data to create a BiDataset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BiDataset we want to update
   *   }
   * })
   */
  upsert<T extends BiDatasetUpsertArgs>(args: Prisma.SelectSubset<T, BiDatasetUpsertArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BiDatasets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetCountArgs} args - Arguments to filter BiDatasets to count.
   * @example
   * // Count the number of BiDatasets
   * const count = await prisma.biDataset.count({
   *   where: {
   *     // ... the filter for the BiDatasets we want to count
   *   }
   * })
  **/
  count<T extends BiDatasetCountArgs>(
    args?: Prisma.Subset<T, BiDatasetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BiDatasetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BiDataset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BiDatasetAggregateArgs>(args: Prisma.Subset<T, BiDatasetAggregateArgs>): Prisma.PrismaPromise<GetBiDatasetAggregateType<T>>

  /**
   * Group by BiDataset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiDatasetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BiDatasetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BiDatasetGroupByArgs['orderBy'] }
      : { orderBy?: BiDatasetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BiDatasetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBiDatasetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BiDataset model
 */
readonly fields: BiDatasetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BiDataset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BiDatasetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  source<T extends Prisma.BiDataset$sourceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDataset$sourceArgs<ExtArgs>>): Prisma.Prisma__BiSourceClient<runtime.Types.Result.GetResult<Prisma.$BiSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  panels<T extends Prisma.BiDataset$panelsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDataset$panelsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.BiDataset$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDataset$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BiDataset model
 */
export interface BiDatasetFieldRefs {
  readonly id: Prisma.FieldRef<"BiDataset", 'String'>
  readonly name: Prisma.FieldRef<"BiDataset", 'String'>
  readonly sql: Prisma.FieldRef<"BiDataset", 'String'>
  readonly description: Prisma.FieldRef<"BiDataset", 'String'>
  readonly isPublic: Prisma.FieldRef<"BiDataset", 'Boolean'>
  readonly sourceId: Prisma.FieldRef<"BiDataset", 'String'>
  readonly lastRunAt: Prisma.FieldRef<"BiDataset", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"BiDataset", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BiDataset", 'DateTime'>
  readonly userId: Prisma.FieldRef<"BiDataset", 'String'>
}
    

// Custom InputTypes
/**
 * BiDataset findUnique
 */
export type BiDatasetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataset to fetch.
   */
  where: Prisma.BiDatasetWhereUniqueInput
}

/**
 * BiDataset findUniqueOrThrow
 */
export type BiDatasetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataset to fetch.
   */
  where: Prisma.BiDatasetWhereUniqueInput
}

/**
 * BiDataset findFirst
 */
export type BiDatasetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataset to fetch.
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDatasets to fetch.
   */
  orderBy?: Prisma.BiDatasetOrderByWithRelationInput | Prisma.BiDatasetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiDatasets.
   */
  cursor?: Prisma.BiDatasetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDatasets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDatasets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDatasets.
   */
  distinct?: Prisma.BiDatasetScalarFieldEnum | Prisma.BiDatasetScalarFieldEnum[]
}

/**
 * BiDataset findFirstOrThrow
 */
export type BiDatasetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter, which BiDataset to fetch.
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDatasets to fetch.
   */
  orderBy?: Prisma.BiDatasetOrderByWithRelationInput | Prisma.BiDatasetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiDatasets.
   */
  cursor?: Prisma.BiDatasetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDatasets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDatasets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDatasets.
   */
  distinct?: Prisma.BiDatasetScalarFieldEnum | Prisma.BiDatasetScalarFieldEnum[]
}

/**
 * BiDataset findMany
 */
export type BiDatasetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter, which BiDatasets to fetch.
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiDatasets to fetch.
   */
  orderBy?: Prisma.BiDatasetOrderByWithRelationInput | Prisma.BiDatasetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BiDatasets.
   */
  cursor?: Prisma.BiDatasetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiDatasets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiDatasets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiDatasets.
   */
  distinct?: Prisma.BiDatasetScalarFieldEnum | Prisma.BiDatasetScalarFieldEnum[]
}

/**
 * BiDataset create
 */
export type BiDatasetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * The data needed to create a BiDataset.
   */
  data: Prisma.XOR<Prisma.BiDatasetCreateInput, Prisma.BiDatasetUncheckedCreateInput>
}

/**
 * BiDataset createMany
 */
export type BiDatasetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BiDatasets.
   */
  data: Prisma.BiDatasetCreateManyInput | Prisma.BiDatasetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BiDataset createManyAndReturn
 */
export type BiDatasetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * The data used to create many BiDatasets.
   */
  data: Prisma.BiDatasetCreateManyInput | Prisma.BiDatasetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BiDataset update
 */
export type BiDatasetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * The data needed to update a BiDataset.
   */
  data: Prisma.XOR<Prisma.BiDatasetUpdateInput, Prisma.BiDatasetUncheckedUpdateInput>
  /**
   * Choose, which BiDataset to update.
   */
  where: Prisma.BiDatasetWhereUniqueInput
}

/**
 * BiDataset updateMany
 */
export type BiDatasetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BiDatasets.
   */
  data: Prisma.XOR<Prisma.BiDatasetUpdateManyMutationInput, Prisma.BiDatasetUncheckedUpdateManyInput>
  /**
   * Filter which BiDatasets to update
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * Limit how many BiDatasets to update.
   */
  limit?: number
}

/**
 * BiDataset updateManyAndReturn
 */
export type BiDatasetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * The data used to update BiDatasets.
   */
  data: Prisma.XOR<Prisma.BiDatasetUpdateManyMutationInput, Prisma.BiDatasetUncheckedUpdateManyInput>
  /**
   * Filter which BiDatasets to update
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * Limit how many BiDatasets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BiDataset upsert
 */
export type BiDatasetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * The filter to search for the BiDataset to update in case it exists.
   */
  where: Prisma.BiDatasetWhereUniqueInput
  /**
   * In case the BiDataset found by the `where` argument doesn't exist, create a new BiDataset with this data.
   */
  create: Prisma.XOR<Prisma.BiDatasetCreateInput, Prisma.BiDatasetUncheckedCreateInput>
  /**
   * In case the BiDataset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BiDatasetUpdateInput, Prisma.BiDatasetUncheckedUpdateInput>
}

/**
 * BiDataset delete
 */
export type BiDatasetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  /**
   * Filter which BiDataset to delete.
   */
  where: Prisma.BiDatasetWhereUniqueInput
}

/**
 * BiDataset deleteMany
 */
export type BiDatasetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiDatasets to delete
   */
  where?: Prisma.BiDatasetWhereInput
  /**
   * Limit how many BiDatasets to delete.
   */
  limit?: number
}

/**
 * BiDataset.source
 */
export type BiDataset$sourceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiSource
   */
  select?: Prisma.BiSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiSource
   */
  omit?: Prisma.BiSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiSourceInclude<ExtArgs> | null
  where?: Prisma.BiSourceWhereInput
}

/**
 * BiDataset.panels
 */
export type BiDataset$panelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  where?: Prisma.BiPanelWhereInput
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  cursor?: Prisma.BiPanelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiPanelScalarFieldEnum | Prisma.BiPanelScalarFieldEnum[]
}

/**
 * BiDataset.user
 */
export type BiDataset$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * BiDataset without action
 */
export type BiDatasetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
}
