
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BiFilter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BiFilter
 * 
 */
export type BiFilterModel = runtime.Types.Result.DefaultSelection<Prisma.$BiFilterPayload>

export type AggregateBiFilter = {
  _count: BiFilterCountAggregateOutputType | null
  _avg: BiFilterAvgAggregateOutputType | null
  _sum: BiFilterSumAggregateOutputType | null
  _min: BiFilterMinAggregateOutputType | null
  _max: BiFilterMaxAggregateOutputType | null
}

export type BiFilterAvgAggregateOutputType = {
  position: number | null
}

export type BiFilterSumAggregateOutputType = {
  position: number | null
}

export type BiFilterMinAggregateOutputType = {
  id: string | null
  dashboardId: string | null
  name: string | null
  label: string | null
  type: string | null
  position: number | null
}

export type BiFilterMaxAggregateOutputType = {
  id: string | null
  dashboardId: string | null
  name: string | null
  label: string | null
  type: string | null
  position: number | null
}

export type BiFilterCountAggregateOutputType = {
  id: number
  dashboardId: number
  name: number
  label: number
  type: number
  config: number
  position: number
  _all: number
}


export type BiFilterAvgAggregateInputType = {
  position?: true
}

export type BiFilterSumAggregateInputType = {
  position?: true
}

export type BiFilterMinAggregateInputType = {
  id?: true
  dashboardId?: true
  name?: true
  label?: true
  type?: true
  position?: true
}

export type BiFilterMaxAggregateInputType = {
  id?: true
  dashboardId?: true
  name?: true
  label?: true
  type?: true
  position?: true
}

export type BiFilterCountAggregateInputType = {
  id?: true
  dashboardId?: true
  name?: true
  label?: true
  type?: true
  config?: true
  position?: true
  _all?: true
}

export type BiFilterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiFilter to aggregate.
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFilters to fetch.
   */
  orderBy?: Prisma.BiFilterOrderByWithRelationInput | Prisma.BiFilterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BiFilterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFilters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFilters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BiFilters
  **/
  _count?: true | BiFilterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BiFilterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BiFilterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BiFilterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BiFilterMaxAggregateInputType
}

export type GetBiFilterAggregateType<T extends BiFilterAggregateArgs> = {
      [P in keyof T & keyof AggregateBiFilter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBiFilter[P]>
    : Prisma.GetScalarType<T[P], AggregateBiFilter[P]>
}




export type BiFilterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiFilterWhereInput
  orderBy?: Prisma.BiFilterOrderByWithAggregationInput | Prisma.BiFilterOrderByWithAggregationInput[]
  by: Prisma.BiFilterScalarFieldEnum[] | Prisma.BiFilterScalarFieldEnum
  having?: Prisma.BiFilterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BiFilterCountAggregateInputType | true
  _avg?: BiFilterAvgAggregateInputType
  _sum?: BiFilterSumAggregateInputType
  _min?: BiFilterMinAggregateInputType
  _max?: BiFilterMaxAggregateInputType
}

export type BiFilterGroupByOutputType = {
  id: string
  dashboardId: string
  name: string
  label: string
  type: string
  config: runtime.JsonValue | null
  position: number
  _count: BiFilterCountAggregateOutputType | null
  _avg: BiFilterAvgAggregateOutputType | null
  _sum: BiFilterSumAggregateOutputType | null
  _min: BiFilterMinAggregateOutputType | null
  _max: BiFilterMaxAggregateOutputType | null
}

export type GetBiFilterGroupByPayload<T extends BiFilterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BiFilterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BiFilterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BiFilterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BiFilterGroupByOutputType[P]>
      }
    >
  >



export type BiFilterWhereInput = {
  AND?: Prisma.BiFilterWhereInput | Prisma.BiFilterWhereInput[]
  OR?: Prisma.BiFilterWhereInput[]
  NOT?: Prisma.BiFilterWhereInput | Prisma.BiFilterWhereInput[]
  id?: Prisma.StringFilter<"BiFilter"> | string
  dashboardId?: Prisma.StringFilter<"BiFilter"> | string
  name?: Prisma.StringFilter<"BiFilter"> | string
  label?: Prisma.StringFilter<"BiFilter"> | string
  type?: Prisma.StringFilter<"BiFilter"> | string
  config?: Prisma.JsonNullableFilter<"BiFilter">
  position?: Prisma.IntFilter<"BiFilter"> | number
  dashboard?: Prisma.XOR<Prisma.BiDashboardScalarRelationFilter, Prisma.BiDashboardWhereInput>
}

export type BiFilterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  position?: Prisma.SortOrder
  dashboard?: Prisma.BiDashboardOrderByWithRelationInput
}

export type BiFilterWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BiFilterWhereInput | Prisma.BiFilterWhereInput[]
  OR?: Prisma.BiFilterWhereInput[]
  NOT?: Prisma.BiFilterWhereInput | Prisma.BiFilterWhereInput[]
  dashboardId?: Prisma.StringFilter<"BiFilter"> | string
  name?: Prisma.StringFilter<"BiFilter"> | string
  label?: Prisma.StringFilter<"BiFilter"> | string
  type?: Prisma.StringFilter<"BiFilter"> | string
  config?: Prisma.JsonNullableFilter<"BiFilter">
  position?: Prisma.IntFilter<"BiFilter"> | number
  dashboard?: Prisma.XOR<Prisma.BiDashboardScalarRelationFilter, Prisma.BiDashboardWhereInput>
}, "id">

export type BiFilterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.BiFilterCountOrderByAggregateInput
  _avg?: Prisma.BiFilterAvgOrderByAggregateInput
  _max?: Prisma.BiFilterMaxOrderByAggregateInput
  _min?: Prisma.BiFilterMinOrderByAggregateInput
  _sum?: Prisma.BiFilterSumOrderByAggregateInput
}

export type BiFilterScalarWhereWithAggregatesInput = {
  AND?: Prisma.BiFilterScalarWhereWithAggregatesInput | Prisma.BiFilterScalarWhereWithAggregatesInput[]
  OR?: Prisma.BiFilterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BiFilterScalarWhereWithAggregatesInput | Prisma.BiFilterScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BiFilter"> | string
  dashboardId?: Prisma.StringWithAggregatesFilter<"BiFilter"> | string
  name?: Prisma.StringWithAggregatesFilter<"BiFilter"> | string
  label?: Prisma.StringWithAggregatesFilter<"BiFilter"> | string
  type?: Prisma.StringWithAggregatesFilter<"BiFilter"> | string
  config?: Prisma.JsonNullableWithAggregatesFilter<"BiFilter">
  position?: Prisma.IntWithAggregatesFilter<"BiFilter"> | number
}

export type BiFilterCreateInput = {
  id?: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
  dashboard: Prisma.BiDashboardCreateNestedOneWithoutFiltersInput
}

export type BiFilterUncheckedCreateInput = {
  id?: string
  dashboardId: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
}

export type BiFilterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
  dashboard?: Prisma.BiDashboardUpdateOneRequiredWithoutFiltersNestedInput
}

export type BiFilterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BiFilterCreateManyInput = {
  id?: string
  dashboardId: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
}

export type BiFilterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BiFilterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BiFilterListRelationFilter = {
  every?: Prisma.BiFilterWhereInput
  some?: Prisma.BiFilterWhereInput
  none?: Prisma.BiFilterWhereInput
}

export type BiFilterOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BiFilterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type BiFilterAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type BiFilterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type BiFilterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type BiFilterSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type BiFilterCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput> | Prisma.BiFilterCreateWithoutDashboardInput[] | Prisma.BiFilterUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiFilterCreateOrConnectWithoutDashboardInput | Prisma.BiFilterCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.BiFilterCreateManyDashboardInputEnvelope
  connect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
}

export type BiFilterUncheckedCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput> | Prisma.BiFilterCreateWithoutDashboardInput[] | Prisma.BiFilterUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiFilterCreateOrConnectWithoutDashboardInput | Prisma.BiFilterCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.BiFilterCreateManyDashboardInputEnvelope
  connect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
}

export type BiFilterUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput> | Prisma.BiFilterCreateWithoutDashboardInput[] | Prisma.BiFilterUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiFilterCreateOrConnectWithoutDashboardInput | Prisma.BiFilterCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.BiFilterUpsertWithWhereUniqueWithoutDashboardInput | Prisma.BiFilterUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.BiFilterCreateManyDashboardInputEnvelope
  set?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  disconnect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  delete?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  connect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  update?: Prisma.BiFilterUpdateWithWhereUniqueWithoutDashboardInput | Prisma.BiFilterUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.BiFilterUpdateManyWithWhereWithoutDashboardInput | Prisma.BiFilterUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.BiFilterScalarWhereInput | Prisma.BiFilterScalarWhereInput[]
}

export type BiFilterUncheckedUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput> | Prisma.BiFilterCreateWithoutDashboardInput[] | Prisma.BiFilterUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiFilterCreateOrConnectWithoutDashboardInput | Prisma.BiFilterCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.BiFilterUpsertWithWhereUniqueWithoutDashboardInput | Prisma.BiFilterUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.BiFilterCreateManyDashboardInputEnvelope
  set?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  disconnect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  delete?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  connect?: Prisma.BiFilterWhereUniqueInput | Prisma.BiFilterWhereUniqueInput[]
  update?: Prisma.BiFilterUpdateWithWhereUniqueWithoutDashboardInput | Prisma.BiFilterUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.BiFilterUpdateManyWithWhereWithoutDashboardInput | Prisma.BiFilterUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.BiFilterScalarWhereInput | Prisma.BiFilterScalarWhereInput[]
}

export type BiFilterCreateWithoutDashboardInput = {
  id?: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
}

export type BiFilterUncheckedCreateWithoutDashboardInput = {
  id?: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
}

export type BiFilterCreateOrConnectWithoutDashboardInput = {
  where: Prisma.BiFilterWhereUniqueInput
  create: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput>
}

export type BiFilterCreateManyDashboardInputEnvelope = {
  data: Prisma.BiFilterCreateManyDashboardInput | Prisma.BiFilterCreateManyDashboardInput[]
  skipDuplicates?: boolean
}

export type BiFilterUpsertWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.BiFilterWhereUniqueInput
  update: Prisma.XOR<Prisma.BiFilterUpdateWithoutDashboardInput, Prisma.BiFilterUncheckedUpdateWithoutDashboardInput>
  create: Prisma.XOR<Prisma.BiFilterCreateWithoutDashboardInput, Prisma.BiFilterUncheckedCreateWithoutDashboardInput>
}

export type BiFilterUpdateWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.BiFilterWhereUniqueInput
  data: Prisma.XOR<Prisma.BiFilterUpdateWithoutDashboardInput, Prisma.BiFilterUncheckedUpdateWithoutDashboardInput>
}

export type BiFilterUpdateManyWithWhereWithoutDashboardInput = {
  where: Prisma.BiFilterScalarWhereInput
  data: Prisma.XOR<Prisma.BiFilterUpdateManyMutationInput, Prisma.BiFilterUncheckedUpdateManyWithoutDashboardInput>
}

export type BiFilterScalarWhereInput = {
  AND?: Prisma.BiFilterScalarWhereInput | Prisma.BiFilterScalarWhereInput[]
  OR?: Prisma.BiFilterScalarWhereInput[]
  NOT?: Prisma.BiFilterScalarWhereInput | Prisma.BiFilterScalarWhereInput[]
  id?: Prisma.StringFilter<"BiFilter"> | string
  dashboardId?: Prisma.StringFilter<"BiFilter"> | string
  name?: Prisma.StringFilter<"BiFilter"> | string
  label?: Prisma.StringFilter<"BiFilter"> | string
  type?: Prisma.StringFilter<"BiFilter"> | string
  config?: Prisma.JsonNullableFilter<"BiFilter">
  position?: Prisma.IntFilter<"BiFilter"> | number
}

export type BiFilterCreateManyDashboardInput = {
  id?: string
  name: string
  label: string
  type?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: number
}

export type BiFilterUpdateWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BiFilterUncheckedUpdateWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BiFilterUncheckedUpdateManyWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type BiFilterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  name?: boolean
  label?: boolean
  type?: boolean
  config?: boolean
  position?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biFilter"]>

export type BiFilterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  name?: boolean
  label?: boolean
  type?: boolean
  config?: boolean
  position?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biFilter"]>

export type BiFilterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  name?: boolean
  label?: boolean
  type?: boolean
  config?: boolean
  position?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biFilter"]>

export type BiFilterSelectScalar = {
  id?: boolean
  dashboardId?: boolean
  name?: boolean
  label?: boolean
  type?: boolean
  config?: boolean
  position?: boolean
}

export type BiFilterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dashboardId" | "name" | "label" | "type" | "config" | "position", ExtArgs["result"]["biFilter"]>
export type BiFilterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}
export type BiFilterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}
export type BiFilterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
}

export type $BiFilterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BiFilter"
  objects: {
    dashboard: Prisma.$BiDashboardPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dashboardId: string
    name: string
    label: string
    type: string
    config: runtime.JsonValue | null
    position: number
  }, ExtArgs["result"]["biFilter"]>
  composites: {}
}

export type BiFilterGetPayload<S extends boolean | null | undefined | BiFilterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BiFilterPayload, S>

export type BiFilterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BiFilterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BiFilterCountAggregateInputType | true
  }

export interface BiFilterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BiFilter'], meta: { name: 'BiFilter' } }
  /**
   * Find zero or one BiFilter that matches the filter.
   * @param {BiFilterFindUniqueArgs} args - Arguments to find a BiFilter
   * @example
   * // Get one BiFilter
   * const biFilter = await prisma.biFilter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BiFilterFindUniqueArgs>(args: Prisma.SelectSubset<T, BiFilterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BiFilter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BiFilterFindUniqueOrThrowArgs} args - Arguments to find a BiFilter
   * @example
   * // Get one BiFilter
   * const biFilter = await prisma.biFilter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BiFilterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BiFilterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiFilter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterFindFirstArgs} args - Arguments to find a BiFilter
   * @example
   * // Get one BiFilter
   * const biFilter = await prisma.biFilter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BiFilterFindFirstArgs>(args?: Prisma.SelectSubset<T, BiFilterFindFirstArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiFilter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterFindFirstOrThrowArgs} args - Arguments to find a BiFilter
   * @example
   * // Get one BiFilter
   * const biFilter = await prisma.biFilter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BiFilterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BiFilterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BiFilters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BiFilters
   * const biFilters = await prisma.biFilter.findMany()
   * 
   * // Get first 10 BiFilters
   * const biFilters = await prisma.biFilter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const biFilterWithIdOnly = await prisma.biFilter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BiFilterFindManyArgs>(args?: Prisma.SelectSubset<T, BiFilterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BiFilter.
   * @param {BiFilterCreateArgs} args - Arguments to create a BiFilter.
   * @example
   * // Create one BiFilter
   * const BiFilter = await prisma.biFilter.create({
   *   data: {
   *     // ... data to create a BiFilter
   *   }
   * })
   * 
   */
  create<T extends BiFilterCreateArgs>(args: Prisma.SelectSubset<T, BiFilterCreateArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BiFilters.
   * @param {BiFilterCreateManyArgs} args - Arguments to create many BiFilters.
   * @example
   * // Create many BiFilters
   * const biFilter = await prisma.biFilter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BiFilterCreateManyArgs>(args?: Prisma.SelectSubset<T, BiFilterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BiFilters and returns the data saved in the database.
   * @param {BiFilterCreateManyAndReturnArgs} args - Arguments to create many BiFilters.
   * @example
   * // Create many BiFilters
   * const biFilter = await prisma.biFilter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BiFilters and only return the `id`
   * const biFilterWithIdOnly = await prisma.biFilter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BiFilterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BiFilterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BiFilter.
   * @param {BiFilterDeleteArgs} args - Arguments to delete one BiFilter.
   * @example
   * // Delete one BiFilter
   * const BiFilter = await prisma.biFilter.delete({
   *   where: {
   *     // ... filter to delete one BiFilter
   *   }
   * })
   * 
   */
  delete<T extends BiFilterDeleteArgs>(args: Prisma.SelectSubset<T, BiFilterDeleteArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BiFilter.
   * @param {BiFilterUpdateArgs} args - Arguments to update one BiFilter.
   * @example
   * // Update one BiFilter
   * const biFilter = await prisma.biFilter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BiFilterUpdateArgs>(args: Prisma.SelectSubset<T, BiFilterUpdateArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BiFilters.
   * @param {BiFilterDeleteManyArgs} args - Arguments to filter BiFilters to delete.
   * @example
   * // Delete a few BiFilters
   * const { count } = await prisma.biFilter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BiFilterDeleteManyArgs>(args?: Prisma.SelectSubset<T, BiFilterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiFilters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BiFilters
   * const biFilter = await prisma.biFilter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BiFilterUpdateManyArgs>(args: Prisma.SelectSubset<T, BiFilterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiFilters and returns the data updated in the database.
   * @param {BiFilterUpdateManyAndReturnArgs} args - Arguments to update many BiFilters.
   * @example
   * // Update many BiFilters
   * const biFilter = await prisma.biFilter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BiFilters and only return the `id`
   * const biFilterWithIdOnly = await prisma.biFilter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BiFilterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BiFilterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BiFilter.
   * @param {BiFilterUpsertArgs} args - Arguments to update or create a BiFilter.
   * @example
   * // Update or create a BiFilter
   * const biFilter = await prisma.biFilter.upsert({
   *   create: {
   *     // ... data to create a BiFilter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BiFilter we want to update
   *   }
   * })
   */
  upsert<T extends BiFilterUpsertArgs>(args: Prisma.SelectSubset<T, BiFilterUpsertArgs<ExtArgs>>): Prisma.Prisma__BiFilterClient<runtime.Types.Result.GetResult<Prisma.$BiFilterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BiFilters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterCountArgs} args - Arguments to filter BiFilters to count.
   * @example
   * // Count the number of BiFilters
   * const count = await prisma.biFilter.count({
   *   where: {
   *     // ... the filter for the BiFilters we want to count
   *   }
   * })
  **/
  count<T extends BiFilterCountArgs>(
    args?: Prisma.Subset<T, BiFilterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BiFilterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BiFilter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BiFilterAggregateArgs>(args: Prisma.Subset<T, BiFilterAggregateArgs>): Prisma.PrismaPromise<GetBiFilterAggregateType<T>>

  /**
   * Group by BiFilter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFilterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BiFilterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BiFilterGroupByArgs['orderBy'] }
      : { orderBy?: BiFilterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BiFilterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBiFilterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BiFilter model
 */
readonly fields: BiFilterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BiFilter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BiFilterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dashboard<T extends Prisma.BiDashboardDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDashboardDefaultArgs<ExtArgs>>): Prisma.Prisma__BiDashboardClient<runtime.Types.Result.GetResult<Prisma.$BiDashboardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BiFilter model
 */
export interface BiFilterFieldRefs {
  readonly id: Prisma.FieldRef<"BiFilter", 'String'>
  readonly dashboardId: Prisma.FieldRef<"BiFilter", 'String'>
  readonly name: Prisma.FieldRef<"BiFilter", 'String'>
  readonly label: Prisma.FieldRef<"BiFilter", 'String'>
  readonly type: Prisma.FieldRef<"BiFilter", 'String'>
  readonly config: Prisma.FieldRef<"BiFilter", 'Json'>
  readonly position: Prisma.FieldRef<"BiFilter", 'Int'>
}
    

// Custom InputTypes
/**
 * BiFilter findUnique
 */
export type BiFilterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter, which BiFilter to fetch.
   */
  where: Prisma.BiFilterWhereUniqueInput
}

/**
 * BiFilter findUniqueOrThrow
 */
export type BiFilterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter, which BiFilter to fetch.
   */
  where: Prisma.BiFilterWhereUniqueInput
}

/**
 * BiFilter findFirst
 */
export type BiFilterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter, which BiFilter to fetch.
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFilters to fetch.
   */
  orderBy?: Prisma.BiFilterOrderByWithRelationInput | Prisma.BiFilterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiFilters.
   */
  cursor?: Prisma.BiFilterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFilters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFilters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFilters.
   */
  distinct?: Prisma.BiFilterScalarFieldEnum | Prisma.BiFilterScalarFieldEnum[]
}

/**
 * BiFilter findFirstOrThrow
 */
export type BiFilterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter, which BiFilter to fetch.
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFilters to fetch.
   */
  orderBy?: Prisma.BiFilterOrderByWithRelationInput | Prisma.BiFilterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiFilters.
   */
  cursor?: Prisma.BiFilterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFilters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFilters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFilters.
   */
  distinct?: Prisma.BiFilterScalarFieldEnum | Prisma.BiFilterScalarFieldEnum[]
}

/**
 * BiFilter findMany
 */
export type BiFilterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter, which BiFilters to fetch.
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFilters to fetch.
   */
  orderBy?: Prisma.BiFilterOrderByWithRelationInput | Prisma.BiFilterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BiFilters.
   */
  cursor?: Prisma.BiFilterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFilters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFilters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFilters.
   */
  distinct?: Prisma.BiFilterScalarFieldEnum | Prisma.BiFilterScalarFieldEnum[]
}

/**
 * BiFilter create
 */
export type BiFilterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * The data needed to create a BiFilter.
   */
  data: Prisma.XOR<Prisma.BiFilterCreateInput, Prisma.BiFilterUncheckedCreateInput>
}

/**
 * BiFilter createMany
 */
export type BiFilterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BiFilters.
   */
  data: Prisma.BiFilterCreateManyInput | Prisma.BiFilterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BiFilter createManyAndReturn
 */
export type BiFilterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * The data used to create many BiFilters.
   */
  data: Prisma.BiFilterCreateManyInput | Prisma.BiFilterCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BiFilter update
 */
export type BiFilterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * The data needed to update a BiFilter.
   */
  data: Prisma.XOR<Prisma.BiFilterUpdateInput, Prisma.BiFilterUncheckedUpdateInput>
  /**
   * Choose, which BiFilter to update.
   */
  where: Prisma.BiFilterWhereUniqueInput
}

/**
 * BiFilter updateMany
 */
export type BiFilterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BiFilters.
   */
  data: Prisma.XOR<Prisma.BiFilterUpdateManyMutationInput, Prisma.BiFilterUncheckedUpdateManyInput>
  /**
   * Filter which BiFilters to update
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * Limit how many BiFilters to update.
   */
  limit?: number
}

/**
 * BiFilter updateManyAndReturn
 */
export type BiFilterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * The data used to update BiFilters.
   */
  data: Prisma.XOR<Prisma.BiFilterUpdateManyMutationInput, Prisma.BiFilterUncheckedUpdateManyInput>
  /**
   * Filter which BiFilters to update
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * Limit how many BiFilters to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BiFilter upsert
 */
export type BiFilterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * The filter to search for the BiFilter to update in case it exists.
   */
  where: Prisma.BiFilterWhereUniqueInput
  /**
   * In case the BiFilter found by the `where` argument doesn't exist, create a new BiFilter with this data.
   */
  create: Prisma.XOR<Prisma.BiFilterCreateInput, Prisma.BiFilterUncheckedCreateInput>
  /**
   * In case the BiFilter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BiFilterUpdateInput, Prisma.BiFilterUncheckedUpdateInput>
}

/**
 * BiFilter delete
 */
export type BiFilterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
  /**
   * Filter which BiFilter to delete.
   */
  where: Prisma.BiFilterWhereUniqueInput
}

/**
 * BiFilter deleteMany
 */
export type BiFilterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiFilters to delete
   */
  where?: Prisma.BiFilterWhereInput
  /**
   * Limit how many BiFilters to delete.
   */
  limit?: number
}

/**
 * BiFilter without action
 */
export type BiFilterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFilter
   */
  select?: Prisma.BiFilterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFilter
   */
  omit?: Prisma.BiFilterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFilterInclude<ExtArgs> | null
}
