
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BiFolder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BiFolder
 * 
 */
export type BiFolderModel = runtime.Types.Result.DefaultSelection<Prisma.$BiFolderPayload>

export type AggregateBiFolder = {
  _count: BiFolderCountAggregateOutputType | null
  _min: BiFolderMinAggregateOutputType | null
  _max: BiFolderMaxAggregateOutputType | null
}

export type BiFolderMinAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  createdAt: Date | null
}

export type BiFolderMaxAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  createdAt: Date | null
}

export type BiFolderCountAggregateOutputType = {
  id: number
  name: number
  parentId: number
  createdAt: number
  _all: number
}


export type BiFolderMinAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
}

export type BiFolderMaxAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
}

export type BiFolderCountAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
  _all?: true
}

export type BiFolderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiFolder to aggregate.
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFolders to fetch.
   */
  orderBy?: Prisma.BiFolderOrderByWithRelationInput | Prisma.BiFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BiFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BiFolders
  **/
  _count?: true | BiFolderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BiFolderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BiFolderMaxAggregateInputType
}

export type GetBiFolderAggregateType<T extends BiFolderAggregateArgs> = {
      [P in keyof T & keyof AggregateBiFolder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBiFolder[P]>
    : Prisma.GetScalarType<T[P], AggregateBiFolder[P]>
}




export type BiFolderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiFolderWhereInput
  orderBy?: Prisma.BiFolderOrderByWithAggregationInput | Prisma.BiFolderOrderByWithAggregationInput[]
  by: Prisma.BiFolderScalarFieldEnum[] | Prisma.BiFolderScalarFieldEnum
  having?: Prisma.BiFolderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BiFolderCountAggregateInputType | true
  _min?: BiFolderMinAggregateInputType
  _max?: BiFolderMaxAggregateInputType
}

export type BiFolderGroupByOutputType = {
  id: string
  name: string
  parentId: string | null
  createdAt: Date
  _count: BiFolderCountAggregateOutputType | null
  _min: BiFolderMinAggregateOutputType | null
  _max: BiFolderMaxAggregateOutputType | null
}

export type GetBiFolderGroupByPayload<T extends BiFolderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BiFolderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BiFolderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BiFolderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BiFolderGroupByOutputType[P]>
      }
    >
  >



export type BiFolderWhereInput = {
  AND?: Prisma.BiFolderWhereInput | Prisma.BiFolderWhereInput[]
  OR?: Prisma.BiFolderWhereInput[]
  NOT?: Prisma.BiFolderWhereInput | Prisma.BiFolderWhereInput[]
  id?: Prisma.StringFilter<"BiFolder"> | string
  name?: Prisma.StringFilter<"BiFolder"> | string
  parentId?: Prisma.StringNullableFilter<"BiFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BiFolder"> | Date | string
  parent?: Prisma.XOR<Prisma.BiFolderNullableScalarRelationFilter, Prisma.BiFolderWhereInput> | null
  children?: Prisma.BiFolderListRelationFilter
  dashboards?: Prisma.BiDashboardListRelationFilter
}

export type BiFolderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  parent?: Prisma.BiFolderOrderByWithRelationInput
  children?: Prisma.BiFolderOrderByRelationAggregateInput
  dashboards?: Prisma.BiDashboardOrderByRelationAggregateInput
}

export type BiFolderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BiFolderWhereInput | Prisma.BiFolderWhereInput[]
  OR?: Prisma.BiFolderWhereInput[]
  NOT?: Prisma.BiFolderWhereInput | Prisma.BiFolderWhereInput[]
  name?: Prisma.StringFilter<"BiFolder"> | string
  parentId?: Prisma.StringNullableFilter<"BiFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BiFolder"> | Date | string
  parent?: Prisma.XOR<Prisma.BiFolderNullableScalarRelationFilter, Prisma.BiFolderWhereInput> | null
  children?: Prisma.BiFolderListRelationFilter
  dashboards?: Prisma.BiDashboardListRelationFilter
}, "id">

export type BiFolderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BiFolderCountOrderByAggregateInput
  _max?: Prisma.BiFolderMaxOrderByAggregateInput
  _min?: Prisma.BiFolderMinOrderByAggregateInput
}

export type BiFolderScalarWhereWithAggregatesInput = {
  AND?: Prisma.BiFolderScalarWhereWithAggregatesInput | Prisma.BiFolderScalarWhereWithAggregatesInput[]
  OR?: Prisma.BiFolderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BiFolderScalarWhereWithAggregatesInput | Prisma.BiFolderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BiFolder"> | string
  name?: Prisma.StringWithAggregatesFilter<"BiFolder"> | string
  parentId?: Prisma.StringNullableWithAggregatesFilter<"BiFolder"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BiFolder"> | Date | string
}

export type BiFolderCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  parent?: Prisma.BiFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.BiFolderCreateNestedManyWithoutParentInput
  dashboards?: Prisma.BiDashboardCreateNestedManyWithoutFolderInput
}

export type BiFolderUncheckedCreateInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  children?: Prisma.BiFolderUncheckedCreateNestedManyWithoutParentInput
  dashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutFolderInput
}

export type BiFolderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.BiFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.BiFolderUpdateManyWithoutParentNestedInput
  dashboards?: Prisma.BiDashboardUpdateManyWithoutFolderNestedInput
}

export type BiFolderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.BiFolderUncheckedUpdateManyWithoutParentNestedInput
  dashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutFolderNestedInput
}

export type BiFolderCreateManyInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
}

export type BiFolderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiFolderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiFolderNullableScalarRelationFilter = {
  is?: Prisma.BiFolderWhereInput | null
  isNot?: Prisma.BiFolderWhereInput | null
}

export type BiFolderListRelationFilter = {
  every?: Prisma.BiFolderWhereInput
  some?: Prisma.BiFolderWhereInput
  none?: Prisma.BiFolderWhereInput
}

export type BiFolderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BiFolderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BiFolderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BiFolderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BiFolderCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutChildrenInput, Prisma.BiFolderUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutChildrenInput
  connect?: Prisma.BiFolderWhereUniqueInput
}

export type BiFolderCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput> | Prisma.BiFolderCreateWithoutParentInput[] | Prisma.BiFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutParentInput | Prisma.BiFolderCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.BiFolderCreateManyParentInputEnvelope
  connect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
}

export type BiFolderUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput> | Prisma.BiFolderCreateWithoutParentInput[] | Prisma.BiFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutParentInput | Prisma.BiFolderCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.BiFolderCreateManyParentInputEnvelope
  connect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
}

export type BiFolderUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutChildrenInput, Prisma.BiFolderUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.BiFolderUpsertWithoutChildrenInput
  disconnect?: Prisma.BiFolderWhereInput | boolean
  delete?: Prisma.BiFolderWhereInput | boolean
  connect?: Prisma.BiFolderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BiFolderUpdateToOneWithWhereWithoutChildrenInput, Prisma.BiFolderUpdateWithoutChildrenInput>, Prisma.BiFolderUncheckedUpdateWithoutChildrenInput>
}

export type BiFolderUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput> | Prisma.BiFolderCreateWithoutParentInput[] | Prisma.BiFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutParentInput | Prisma.BiFolderCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.BiFolderUpsertWithWhereUniqueWithoutParentInput | Prisma.BiFolderUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.BiFolderCreateManyParentInputEnvelope
  set?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  disconnect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  delete?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  connect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  update?: Prisma.BiFolderUpdateWithWhereUniqueWithoutParentInput | Prisma.BiFolderUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.BiFolderUpdateManyWithWhereWithoutParentInput | Prisma.BiFolderUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.BiFolderScalarWhereInput | Prisma.BiFolderScalarWhereInput[]
}

export type BiFolderUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput> | Prisma.BiFolderCreateWithoutParentInput[] | Prisma.BiFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutParentInput | Prisma.BiFolderCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.BiFolderUpsertWithWhereUniqueWithoutParentInput | Prisma.BiFolderUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.BiFolderCreateManyParentInputEnvelope
  set?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  disconnect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  delete?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  connect?: Prisma.BiFolderWhereUniqueInput | Prisma.BiFolderWhereUniqueInput[]
  update?: Prisma.BiFolderUpdateWithWhereUniqueWithoutParentInput | Prisma.BiFolderUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.BiFolderUpdateManyWithWhereWithoutParentInput | Prisma.BiFolderUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.BiFolderScalarWhereInput | Prisma.BiFolderScalarWhereInput[]
}

export type BiFolderCreateNestedOneWithoutDashboardsInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutDashboardsInput, Prisma.BiFolderUncheckedCreateWithoutDashboardsInput>
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutDashboardsInput
  connect?: Prisma.BiFolderWhereUniqueInput
}

export type BiFolderUpdateOneWithoutDashboardsNestedInput = {
  create?: Prisma.XOR<Prisma.BiFolderCreateWithoutDashboardsInput, Prisma.BiFolderUncheckedCreateWithoutDashboardsInput>
  connectOrCreate?: Prisma.BiFolderCreateOrConnectWithoutDashboardsInput
  upsert?: Prisma.BiFolderUpsertWithoutDashboardsInput
  disconnect?: Prisma.BiFolderWhereInput | boolean
  delete?: Prisma.BiFolderWhereInput | boolean
  connect?: Prisma.BiFolderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BiFolderUpdateToOneWithWhereWithoutDashboardsInput, Prisma.BiFolderUpdateWithoutDashboardsInput>, Prisma.BiFolderUncheckedUpdateWithoutDashboardsInput>
}

export type BiFolderCreateWithoutChildrenInput = {
  id?: string
  name: string
  createdAt?: Date | string
  parent?: Prisma.BiFolderCreateNestedOneWithoutChildrenInput
  dashboards?: Prisma.BiDashboardCreateNestedManyWithoutFolderInput
}

export type BiFolderUncheckedCreateWithoutChildrenInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  dashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutFolderInput
}

export type BiFolderCreateOrConnectWithoutChildrenInput = {
  where: Prisma.BiFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutChildrenInput, Prisma.BiFolderUncheckedCreateWithoutChildrenInput>
}

export type BiFolderCreateWithoutParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  children?: Prisma.BiFolderCreateNestedManyWithoutParentInput
  dashboards?: Prisma.BiDashboardCreateNestedManyWithoutFolderInput
}

export type BiFolderUncheckedCreateWithoutParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  children?: Prisma.BiFolderUncheckedCreateNestedManyWithoutParentInput
  dashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutFolderInput
}

export type BiFolderCreateOrConnectWithoutParentInput = {
  where: Prisma.BiFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput>
}

export type BiFolderCreateManyParentInputEnvelope = {
  data: Prisma.BiFolderCreateManyParentInput | Prisma.BiFolderCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type BiFolderUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.BiFolderUpdateWithoutChildrenInput, Prisma.BiFolderUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutChildrenInput, Prisma.BiFolderUncheckedCreateWithoutChildrenInput>
  where?: Prisma.BiFolderWhereInput
}

export type BiFolderUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.BiFolderWhereInput
  data: Prisma.XOR<Prisma.BiFolderUpdateWithoutChildrenInput, Prisma.BiFolderUncheckedUpdateWithoutChildrenInput>
}

export type BiFolderUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.BiFolderUpdateOneWithoutChildrenNestedInput
  dashboards?: Prisma.BiDashboardUpdateManyWithoutFolderNestedInput
}

export type BiFolderUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutFolderNestedInput
}

export type BiFolderUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.BiFolderWhereUniqueInput
  update: Prisma.XOR<Prisma.BiFolderUpdateWithoutParentInput, Prisma.BiFolderUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutParentInput, Prisma.BiFolderUncheckedCreateWithoutParentInput>
}

export type BiFolderUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.BiFolderWhereUniqueInput
  data: Prisma.XOR<Prisma.BiFolderUpdateWithoutParentInput, Prisma.BiFolderUncheckedUpdateWithoutParentInput>
}

export type BiFolderUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.BiFolderScalarWhereInput
  data: Prisma.XOR<Prisma.BiFolderUpdateManyMutationInput, Prisma.BiFolderUncheckedUpdateManyWithoutParentInput>
}

export type BiFolderScalarWhereInput = {
  AND?: Prisma.BiFolderScalarWhereInput | Prisma.BiFolderScalarWhereInput[]
  OR?: Prisma.BiFolderScalarWhereInput[]
  NOT?: Prisma.BiFolderScalarWhereInput | Prisma.BiFolderScalarWhereInput[]
  id?: Prisma.StringFilter<"BiFolder"> | string
  name?: Prisma.StringFilter<"BiFolder"> | string
  parentId?: Prisma.StringNullableFilter<"BiFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BiFolder"> | Date | string
}

export type BiFolderCreateWithoutDashboardsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  parent?: Prisma.BiFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.BiFolderCreateNestedManyWithoutParentInput
}

export type BiFolderUncheckedCreateWithoutDashboardsInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  children?: Prisma.BiFolderUncheckedCreateNestedManyWithoutParentInput
}

export type BiFolderCreateOrConnectWithoutDashboardsInput = {
  where: Prisma.BiFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutDashboardsInput, Prisma.BiFolderUncheckedCreateWithoutDashboardsInput>
}

export type BiFolderUpsertWithoutDashboardsInput = {
  update: Prisma.XOR<Prisma.BiFolderUpdateWithoutDashboardsInput, Prisma.BiFolderUncheckedUpdateWithoutDashboardsInput>
  create: Prisma.XOR<Prisma.BiFolderCreateWithoutDashboardsInput, Prisma.BiFolderUncheckedCreateWithoutDashboardsInput>
  where?: Prisma.BiFolderWhereInput
}

export type BiFolderUpdateToOneWithWhereWithoutDashboardsInput = {
  where?: Prisma.BiFolderWhereInput
  data: Prisma.XOR<Prisma.BiFolderUpdateWithoutDashboardsInput, Prisma.BiFolderUncheckedUpdateWithoutDashboardsInput>
}

export type BiFolderUpdateWithoutDashboardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.BiFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.BiFolderUpdateManyWithoutParentNestedInput
}

export type BiFolderUncheckedUpdateWithoutDashboardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.BiFolderUncheckedUpdateManyWithoutParentNestedInput
}

export type BiFolderCreateManyParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
}

export type BiFolderUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.BiFolderUpdateManyWithoutParentNestedInput
  dashboards?: Prisma.BiDashboardUpdateManyWithoutFolderNestedInput
}

export type BiFolderUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.BiFolderUncheckedUpdateManyWithoutParentNestedInput
  dashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutFolderNestedInput
}

export type BiFolderUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BiFolderCountOutputType
 */

export type BiFolderCountOutputType = {
  children: number
  dashboards: number
}

export type BiFolderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | BiFolderCountOutputTypeCountChildrenArgs
  dashboards?: boolean | BiFolderCountOutputTypeCountDashboardsArgs
}

/**
 * BiFolderCountOutputType without action
 */
export type BiFolderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolderCountOutputType
   */
  select?: Prisma.BiFolderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BiFolderCountOutputType without action
 */
export type BiFolderCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiFolderWhereInput
}

/**
 * BiFolderCountOutputType without action
 */
export type BiFolderCountOutputTypeCountDashboardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDashboardWhereInput
}


export type BiFolderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
  children?: boolean | Prisma.BiFolder$childrenArgs<ExtArgs>
  dashboards?: boolean | Prisma.BiFolder$dashboardsArgs<ExtArgs>
  _count?: boolean | Prisma.BiFolderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["biFolder"]>

export type BiFolderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
}, ExtArgs["result"]["biFolder"]>

export type BiFolderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
}, ExtArgs["result"]["biFolder"]>

export type BiFolderSelectScalar = {
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
}

export type BiFolderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "parentId" | "createdAt", ExtArgs["result"]["biFolder"]>
export type BiFolderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
  children?: boolean | Prisma.BiFolder$childrenArgs<ExtArgs>
  dashboards?: boolean | Prisma.BiFolder$dashboardsArgs<ExtArgs>
  _count?: boolean | Prisma.BiFolderCountOutputTypeDefaultArgs<ExtArgs>
}
export type BiFolderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
}
export type BiFolderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.BiFolder$parentArgs<ExtArgs>
}

export type $BiFolderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BiFolder"
  objects: {
    parent: Prisma.$BiFolderPayload<ExtArgs> | null
    children: Prisma.$BiFolderPayload<ExtArgs>[]
    dashboards: Prisma.$BiDashboardPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    parentId: string | null
    createdAt: Date
  }, ExtArgs["result"]["biFolder"]>
  composites: {}
}

export type BiFolderGetPayload<S extends boolean | null | undefined | BiFolderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BiFolderPayload, S>

export type BiFolderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BiFolderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BiFolderCountAggregateInputType | true
  }

export interface BiFolderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BiFolder'], meta: { name: 'BiFolder' } }
  /**
   * Find zero or one BiFolder that matches the filter.
   * @param {BiFolderFindUniqueArgs} args - Arguments to find a BiFolder
   * @example
   * // Get one BiFolder
   * const biFolder = await prisma.biFolder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BiFolderFindUniqueArgs>(args: Prisma.SelectSubset<T, BiFolderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BiFolder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BiFolderFindUniqueOrThrowArgs} args - Arguments to find a BiFolder
   * @example
   * // Get one BiFolder
   * const biFolder = await prisma.biFolder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BiFolderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BiFolderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiFolder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderFindFirstArgs} args - Arguments to find a BiFolder
   * @example
   * // Get one BiFolder
   * const biFolder = await prisma.biFolder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BiFolderFindFirstArgs>(args?: Prisma.SelectSubset<T, BiFolderFindFirstArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiFolder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderFindFirstOrThrowArgs} args - Arguments to find a BiFolder
   * @example
   * // Get one BiFolder
   * const biFolder = await prisma.biFolder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BiFolderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BiFolderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BiFolders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BiFolders
   * const biFolders = await prisma.biFolder.findMany()
   * 
   * // Get first 10 BiFolders
   * const biFolders = await prisma.biFolder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const biFolderWithIdOnly = await prisma.biFolder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BiFolderFindManyArgs>(args?: Prisma.SelectSubset<T, BiFolderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BiFolder.
   * @param {BiFolderCreateArgs} args - Arguments to create a BiFolder.
   * @example
   * // Create one BiFolder
   * const BiFolder = await prisma.biFolder.create({
   *   data: {
   *     // ... data to create a BiFolder
   *   }
   * })
   * 
   */
  create<T extends BiFolderCreateArgs>(args: Prisma.SelectSubset<T, BiFolderCreateArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BiFolders.
   * @param {BiFolderCreateManyArgs} args - Arguments to create many BiFolders.
   * @example
   * // Create many BiFolders
   * const biFolder = await prisma.biFolder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BiFolderCreateManyArgs>(args?: Prisma.SelectSubset<T, BiFolderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BiFolders and returns the data saved in the database.
   * @param {BiFolderCreateManyAndReturnArgs} args - Arguments to create many BiFolders.
   * @example
   * // Create many BiFolders
   * const biFolder = await prisma.biFolder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BiFolders and only return the `id`
   * const biFolderWithIdOnly = await prisma.biFolder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BiFolderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BiFolderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BiFolder.
   * @param {BiFolderDeleteArgs} args - Arguments to delete one BiFolder.
   * @example
   * // Delete one BiFolder
   * const BiFolder = await prisma.biFolder.delete({
   *   where: {
   *     // ... filter to delete one BiFolder
   *   }
   * })
   * 
   */
  delete<T extends BiFolderDeleteArgs>(args: Prisma.SelectSubset<T, BiFolderDeleteArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BiFolder.
   * @param {BiFolderUpdateArgs} args - Arguments to update one BiFolder.
   * @example
   * // Update one BiFolder
   * const biFolder = await prisma.biFolder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BiFolderUpdateArgs>(args: Prisma.SelectSubset<T, BiFolderUpdateArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BiFolders.
   * @param {BiFolderDeleteManyArgs} args - Arguments to filter BiFolders to delete.
   * @example
   * // Delete a few BiFolders
   * const { count } = await prisma.biFolder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BiFolderDeleteManyArgs>(args?: Prisma.SelectSubset<T, BiFolderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiFolders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BiFolders
   * const biFolder = await prisma.biFolder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BiFolderUpdateManyArgs>(args: Prisma.SelectSubset<T, BiFolderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiFolders and returns the data updated in the database.
   * @param {BiFolderUpdateManyAndReturnArgs} args - Arguments to update many BiFolders.
   * @example
   * // Update many BiFolders
   * const biFolder = await prisma.biFolder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BiFolders and only return the `id`
   * const biFolderWithIdOnly = await prisma.biFolder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BiFolderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BiFolderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BiFolder.
   * @param {BiFolderUpsertArgs} args - Arguments to update or create a BiFolder.
   * @example
   * // Update or create a BiFolder
   * const biFolder = await prisma.biFolder.upsert({
   *   create: {
   *     // ... data to create a BiFolder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BiFolder we want to update
   *   }
   * })
   */
  upsert<T extends BiFolderUpsertArgs>(args: Prisma.SelectSubset<T, BiFolderUpsertArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BiFolders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderCountArgs} args - Arguments to filter BiFolders to count.
   * @example
   * // Count the number of BiFolders
   * const count = await prisma.biFolder.count({
   *   where: {
   *     // ... the filter for the BiFolders we want to count
   *   }
   * })
  **/
  count<T extends BiFolderCountArgs>(
    args?: Prisma.Subset<T, BiFolderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BiFolderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BiFolder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BiFolderAggregateArgs>(args: Prisma.Subset<T, BiFolderAggregateArgs>): Prisma.PrismaPromise<GetBiFolderAggregateType<T>>

  /**
   * Group by BiFolder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiFolderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BiFolderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BiFolderGroupByArgs['orderBy'] }
      : { orderBy?: BiFolderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BiFolderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBiFolderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BiFolder model
 */
readonly fields: BiFolderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BiFolder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BiFolderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  parent<T extends Prisma.BiFolder$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiFolder$parentArgs<ExtArgs>>): Prisma.Prisma__BiFolderClient<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.BiFolder$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiFolder$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiFolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  dashboards<T extends Prisma.BiFolder$dashboardsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiFolder$dashboardsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDashboardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BiFolder model
 */
export interface BiFolderFieldRefs {
  readonly id: Prisma.FieldRef<"BiFolder", 'String'>
  readonly name: Prisma.FieldRef<"BiFolder", 'String'>
  readonly parentId: Prisma.FieldRef<"BiFolder", 'String'>
  readonly createdAt: Prisma.FieldRef<"BiFolder", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BiFolder findUnique
 */
export type BiFolderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter, which BiFolder to fetch.
   */
  where: Prisma.BiFolderWhereUniqueInput
}

/**
 * BiFolder findUniqueOrThrow
 */
export type BiFolderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter, which BiFolder to fetch.
   */
  where: Prisma.BiFolderWhereUniqueInput
}

/**
 * BiFolder findFirst
 */
export type BiFolderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter, which BiFolder to fetch.
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFolders to fetch.
   */
  orderBy?: Prisma.BiFolderOrderByWithRelationInput | Prisma.BiFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiFolders.
   */
  cursor?: Prisma.BiFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFolders.
   */
  distinct?: Prisma.BiFolderScalarFieldEnum | Prisma.BiFolderScalarFieldEnum[]
}

/**
 * BiFolder findFirstOrThrow
 */
export type BiFolderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter, which BiFolder to fetch.
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFolders to fetch.
   */
  orderBy?: Prisma.BiFolderOrderByWithRelationInput | Prisma.BiFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiFolders.
   */
  cursor?: Prisma.BiFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFolders.
   */
  distinct?: Prisma.BiFolderScalarFieldEnum | Prisma.BiFolderScalarFieldEnum[]
}

/**
 * BiFolder findMany
 */
export type BiFolderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter, which BiFolders to fetch.
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiFolders to fetch.
   */
  orderBy?: Prisma.BiFolderOrderByWithRelationInput | Prisma.BiFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BiFolders.
   */
  cursor?: Prisma.BiFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiFolders.
   */
  distinct?: Prisma.BiFolderScalarFieldEnum | Prisma.BiFolderScalarFieldEnum[]
}

/**
 * BiFolder create
 */
export type BiFolderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * The data needed to create a BiFolder.
   */
  data: Prisma.XOR<Prisma.BiFolderCreateInput, Prisma.BiFolderUncheckedCreateInput>
}

/**
 * BiFolder createMany
 */
export type BiFolderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BiFolders.
   */
  data: Prisma.BiFolderCreateManyInput | Prisma.BiFolderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BiFolder createManyAndReturn
 */
export type BiFolderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * The data used to create many BiFolders.
   */
  data: Prisma.BiFolderCreateManyInput | Prisma.BiFolderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BiFolder update
 */
export type BiFolderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * The data needed to update a BiFolder.
   */
  data: Prisma.XOR<Prisma.BiFolderUpdateInput, Prisma.BiFolderUncheckedUpdateInput>
  /**
   * Choose, which BiFolder to update.
   */
  where: Prisma.BiFolderWhereUniqueInput
}

/**
 * BiFolder updateMany
 */
export type BiFolderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BiFolders.
   */
  data: Prisma.XOR<Prisma.BiFolderUpdateManyMutationInput, Prisma.BiFolderUncheckedUpdateManyInput>
  /**
   * Filter which BiFolders to update
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * Limit how many BiFolders to update.
   */
  limit?: number
}

/**
 * BiFolder updateManyAndReturn
 */
export type BiFolderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * The data used to update BiFolders.
   */
  data: Prisma.XOR<Prisma.BiFolderUpdateManyMutationInput, Prisma.BiFolderUncheckedUpdateManyInput>
  /**
   * Filter which BiFolders to update
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * Limit how many BiFolders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BiFolder upsert
 */
export type BiFolderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * The filter to search for the BiFolder to update in case it exists.
   */
  where: Prisma.BiFolderWhereUniqueInput
  /**
   * In case the BiFolder found by the `where` argument doesn't exist, create a new BiFolder with this data.
   */
  create: Prisma.XOR<Prisma.BiFolderCreateInput, Prisma.BiFolderUncheckedCreateInput>
  /**
   * In case the BiFolder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BiFolderUpdateInput, Prisma.BiFolderUncheckedUpdateInput>
}

/**
 * BiFolder delete
 */
export type BiFolderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  /**
   * Filter which BiFolder to delete.
   */
  where: Prisma.BiFolderWhereUniqueInput
}

/**
 * BiFolder deleteMany
 */
export type BiFolderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiFolders to delete
   */
  where?: Prisma.BiFolderWhereInput
  /**
   * Limit how many BiFolders to delete.
   */
  limit?: number
}

/**
 * BiFolder.parent
 */
export type BiFolder$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  where?: Prisma.BiFolderWhereInput
}

/**
 * BiFolder.children
 */
export type BiFolder$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
  where?: Prisma.BiFolderWhereInput
  orderBy?: Prisma.BiFolderOrderByWithRelationInput | Prisma.BiFolderOrderByWithRelationInput[]
  cursor?: Prisma.BiFolderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiFolderScalarFieldEnum | Prisma.BiFolderScalarFieldEnum[]
}

/**
 * BiFolder.dashboards
 */
export type BiFolder$dashboardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDashboard
   */
  select?: Prisma.BiDashboardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDashboard
   */
  omit?: Prisma.BiDashboardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDashboardInclude<ExtArgs> | null
  where?: Prisma.BiDashboardWhereInput
  orderBy?: Prisma.BiDashboardOrderByWithRelationInput | Prisma.BiDashboardOrderByWithRelationInput[]
  cursor?: Prisma.BiDashboardWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiDashboardScalarFieldEnum | Prisma.BiDashboardScalarFieldEnum[]
}

/**
 * BiFolder without action
 */
export type BiFolderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiFolder
   */
  select?: Prisma.BiFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiFolder
   */
  omit?: Prisma.BiFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiFolderInclude<ExtArgs> | null
}
