
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BiPanel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BiPanel
 * 
 */
export type BiPanelModel = runtime.Types.Result.DefaultSelection<Prisma.$BiPanelPayload>

export type AggregateBiPanel = {
  _count: BiPanelCountAggregateOutputType | null
  _avg: BiPanelAvgAggregateOutputType | null
  _sum: BiPanelSumAggregateOutputType | null
  _min: BiPanelMinAggregateOutputType | null
  _max: BiPanelMaxAggregateOutputType | null
}

export type BiPanelAvgAggregateOutputType = {
  x: number | null
  y: number | null
  w: number | null
  h: number | null
}

export type BiPanelSumAggregateOutputType = {
  x: number | null
  y: number | null
  w: number | null
  h: number | null
}

export type BiPanelMinAggregateOutputType = {
  id: string | null
  dashboardId: string | null
  dataSetId: string | null
  title: string | null
  chartType: string | null
  x: number | null
  y: number | null
  w: number | null
  h: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BiPanelMaxAggregateOutputType = {
  id: string | null
  dashboardId: string | null
  dataSetId: string | null
  title: string | null
  chartType: string | null
  x: number | null
  y: number | null
  w: number | null
  h: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BiPanelCountAggregateOutputType = {
  id: number
  dashboardId: number
  dataSetId: number
  title: number
  chartType: number
  config: number
  x: number
  y: number
  w: number
  h: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BiPanelAvgAggregateInputType = {
  x?: true
  y?: true
  w?: true
  h?: true
}

export type BiPanelSumAggregateInputType = {
  x?: true
  y?: true
  w?: true
  h?: true
}

export type BiPanelMinAggregateInputType = {
  id?: true
  dashboardId?: true
  dataSetId?: true
  title?: true
  chartType?: true
  x?: true
  y?: true
  w?: true
  h?: true
  createdAt?: true
  updatedAt?: true
}

export type BiPanelMaxAggregateInputType = {
  id?: true
  dashboardId?: true
  dataSetId?: true
  title?: true
  chartType?: true
  x?: true
  y?: true
  w?: true
  h?: true
  createdAt?: true
  updatedAt?: true
}

export type BiPanelCountAggregateInputType = {
  id?: true
  dashboardId?: true
  dataSetId?: true
  title?: true
  chartType?: true
  config?: true
  x?: true
  y?: true
  w?: true
  h?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BiPanelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiPanel to aggregate.
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiPanels to fetch.
   */
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BiPanelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiPanels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiPanels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BiPanels
  **/
  _count?: true | BiPanelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BiPanelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BiPanelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BiPanelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BiPanelMaxAggregateInputType
}

export type GetBiPanelAggregateType<T extends BiPanelAggregateArgs> = {
      [P in keyof T & keyof AggregateBiPanel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBiPanel[P]>
    : Prisma.GetScalarType<T[P], AggregateBiPanel[P]>
}




export type BiPanelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiPanelWhereInput
  orderBy?: Prisma.BiPanelOrderByWithAggregationInput | Prisma.BiPanelOrderByWithAggregationInput[]
  by: Prisma.BiPanelScalarFieldEnum[] | Prisma.BiPanelScalarFieldEnum
  having?: Prisma.BiPanelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BiPanelCountAggregateInputType | true
  _avg?: BiPanelAvgAggregateInputType
  _sum?: BiPanelSumAggregateInputType
  _min?: BiPanelMinAggregateInputType
  _max?: BiPanelMaxAggregateInputType
}

export type BiPanelGroupByOutputType = {
  id: string
  dashboardId: string
  dataSetId: string | null
  title: string
  chartType: string
  config: runtime.JsonValue | null
  x: number
  y: number
  w: number
  h: number
  createdAt: Date
  updatedAt: Date
  _count: BiPanelCountAggregateOutputType | null
  _avg: BiPanelAvgAggregateOutputType | null
  _sum: BiPanelSumAggregateOutputType | null
  _min: BiPanelMinAggregateOutputType | null
  _max: BiPanelMaxAggregateOutputType | null
}

export type GetBiPanelGroupByPayload<T extends BiPanelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BiPanelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BiPanelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BiPanelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BiPanelGroupByOutputType[P]>
      }
    >
  >



export type BiPanelWhereInput = {
  AND?: Prisma.BiPanelWhereInput | Prisma.BiPanelWhereInput[]
  OR?: Prisma.BiPanelWhereInput[]
  NOT?: Prisma.BiPanelWhereInput | Prisma.BiPanelWhereInput[]
  id?: Prisma.StringFilter<"BiPanel"> | string
  dashboardId?: Prisma.StringFilter<"BiPanel"> | string
  dataSetId?: Prisma.StringNullableFilter<"BiPanel"> | string | null
  title?: Prisma.StringFilter<"BiPanel"> | string
  chartType?: Prisma.StringFilter<"BiPanel"> | string
  config?: Prisma.JsonNullableFilter<"BiPanel">
  x?: Prisma.IntFilter<"BiPanel"> | number
  y?: Prisma.IntFilter<"BiPanel"> | number
  w?: Prisma.IntFilter<"BiPanel"> | number
  h?: Prisma.IntFilter<"BiPanel"> | number
  createdAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
  dashboard?: Prisma.XOR<Prisma.BiDashboardScalarRelationFilter, Prisma.BiDashboardWhereInput>
  dataSet?: Prisma.XOR<Prisma.BiDatasetNullableScalarRelationFilter, Prisma.BiDatasetWhereInput> | null
}

export type BiPanelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  dataSetId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  chartType?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  dashboard?: Prisma.BiDashboardOrderByWithRelationInput
  dataSet?: Prisma.BiDatasetOrderByWithRelationInput
}

export type BiPanelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BiPanelWhereInput | Prisma.BiPanelWhereInput[]
  OR?: Prisma.BiPanelWhereInput[]
  NOT?: Prisma.BiPanelWhereInput | Prisma.BiPanelWhereInput[]
  dashboardId?: Prisma.StringFilter<"BiPanel"> | string
  dataSetId?: Prisma.StringNullableFilter<"BiPanel"> | string | null
  title?: Prisma.StringFilter<"BiPanel"> | string
  chartType?: Prisma.StringFilter<"BiPanel"> | string
  config?: Prisma.JsonNullableFilter<"BiPanel">
  x?: Prisma.IntFilter<"BiPanel"> | number
  y?: Prisma.IntFilter<"BiPanel"> | number
  w?: Prisma.IntFilter<"BiPanel"> | number
  h?: Prisma.IntFilter<"BiPanel"> | number
  createdAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
  dashboard?: Prisma.XOR<Prisma.BiDashboardScalarRelationFilter, Prisma.BiDashboardWhereInput>
  dataSet?: Prisma.XOR<Prisma.BiDatasetNullableScalarRelationFilter, Prisma.BiDatasetWhereInput> | null
}, "id">

export type BiPanelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  dataSetId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  chartType?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BiPanelCountOrderByAggregateInput
  _avg?: Prisma.BiPanelAvgOrderByAggregateInput
  _max?: Prisma.BiPanelMaxOrderByAggregateInput
  _min?: Prisma.BiPanelMinOrderByAggregateInput
  _sum?: Prisma.BiPanelSumOrderByAggregateInput
}

export type BiPanelScalarWhereWithAggregatesInput = {
  AND?: Prisma.BiPanelScalarWhereWithAggregatesInput | Prisma.BiPanelScalarWhereWithAggregatesInput[]
  OR?: Prisma.BiPanelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BiPanelScalarWhereWithAggregatesInput | Prisma.BiPanelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BiPanel"> | string
  dashboardId?: Prisma.StringWithAggregatesFilter<"BiPanel"> | string
  dataSetId?: Prisma.StringNullableWithAggregatesFilter<"BiPanel"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"BiPanel"> | string
  chartType?: Prisma.StringWithAggregatesFilter<"BiPanel"> | string
  config?: Prisma.JsonNullableWithAggregatesFilter<"BiPanel">
  x?: Prisma.IntWithAggregatesFilter<"BiPanel"> | number
  y?: Prisma.IntWithAggregatesFilter<"BiPanel"> | number
  w?: Prisma.IntWithAggregatesFilter<"BiPanel"> | number
  h?: Prisma.IntWithAggregatesFilter<"BiPanel"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BiPanel"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BiPanel"> | Date | string
}

export type BiPanelCreateInput = {
  id?: string
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  dashboard: Prisma.BiDashboardCreateNestedOneWithoutPanelsInput
  dataSet?: Prisma.BiDatasetCreateNestedOneWithoutPanelsInput
}

export type BiPanelUncheckedCreateInput = {
  id?: string
  dashboardId: string
  dataSetId?: string | null
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dashboard?: Prisma.BiDashboardUpdateOneRequiredWithoutPanelsNestedInput
  dataSet?: Prisma.BiDatasetUpdateOneWithoutPanelsNestedInput
}

export type BiPanelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  dataSetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelCreateManyInput = {
  id?: string
  dashboardId: string
  dataSetId?: string | null
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  dataSetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelListRelationFilter = {
  every?: Prisma.BiPanelWhereInput
  some?: Prisma.BiPanelWhereInput
  none?: Prisma.BiPanelWhereInput
}

export type BiPanelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BiPanelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  dataSetId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  chartType?: Prisma.SortOrder
  config?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BiPanelAvgOrderByAggregateInput = {
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
}

export type BiPanelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  dataSetId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  chartType?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BiPanelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dashboardId?: Prisma.SortOrder
  dataSetId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  chartType?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BiPanelSumOrderByAggregateInput = {
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  w?: Prisma.SortOrder
  h?: Prisma.SortOrder
}

export type BiPanelCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput> | Prisma.BiPanelCreateWithoutDashboardInput[] | Prisma.BiPanelUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDashboardInput | Prisma.BiPanelCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.BiPanelCreateManyDashboardInputEnvelope
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
}

export type BiPanelUncheckedCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput> | Prisma.BiPanelCreateWithoutDashboardInput[] | Prisma.BiPanelUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDashboardInput | Prisma.BiPanelCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.BiPanelCreateManyDashboardInputEnvelope
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
}

export type BiPanelUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput> | Prisma.BiPanelCreateWithoutDashboardInput[] | Prisma.BiPanelUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDashboardInput | Prisma.BiPanelCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.BiPanelUpsertWithWhereUniqueWithoutDashboardInput | Prisma.BiPanelUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.BiPanelCreateManyDashboardInputEnvelope
  set?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  disconnect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  delete?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  update?: Prisma.BiPanelUpdateWithWhereUniqueWithoutDashboardInput | Prisma.BiPanelUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.BiPanelUpdateManyWithWhereWithoutDashboardInput | Prisma.BiPanelUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
}

export type BiPanelUncheckedUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput> | Prisma.BiPanelCreateWithoutDashboardInput[] | Prisma.BiPanelUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDashboardInput | Prisma.BiPanelCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.BiPanelUpsertWithWhereUniqueWithoutDashboardInput | Prisma.BiPanelUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.BiPanelCreateManyDashboardInputEnvelope
  set?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  disconnect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  delete?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  update?: Prisma.BiPanelUpdateWithWhereUniqueWithoutDashboardInput | Prisma.BiPanelUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.BiPanelUpdateManyWithWhereWithoutDashboardInput | Prisma.BiPanelUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
}

export type BiPanelCreateNestedManyWithoutDataSetInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput> | Prisma.BiPanelCreateWithoutDataSetInput[] | Prisma.BiPanelUncheckedCreateWithoutDataSetInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDataSetInput | Prisma.BiPanelCreateOrConnectWithoutDataSetInput[]
  createMany?: Prisma.BiPanelCreateManyDataSetInputEnvelope
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
}

export type BiPanelUncheckedCreateNestedManyWithoutDataSetInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput> | Prisma.BiPanelCreateWithoutDataSetInput[] | Prisma.BiPanelUncheckedCreateWithoutDataSetInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDataSetInput | Prisma.BiPanelCreateOrConnectWithoutDataSetInput[]
  createMany?: Prisma.BiPanelCreateManyDataSetInputEnvelope
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
}

export type BiPanelUpdateManyWithoutDataSetNestedInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput> | Prisma.BiPanelCreateWithoutDataSetInput[] | Prisma.BiPanelUncheckedCreateWithoutDataSetInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDataSetInput | Prisma.BiPanelCreateOrConnectWithoutDataSetInput[]
  upsert?: Prisma.BiPanelUpsertWithWhereUniqueWithoutDataSetInput | Prisma.BiPanelUpsertWithWhereUniqueWithoutDataSetInput[]
  createMany?: Prisma.BiPanelCreateManyDataSetInputEnvelope
  set?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  disconnect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  delete?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  update?: Prisma.BiPanelUpdateWithWhereUniqueWithoutDataSetInput | Prisma.BiPanelUpdateWithWhereUniqueWithoutDataSetInput[]
  updateMany?: Prisma.BiPanelUpdateManyWithWhereWithoutDataSetInput | Prisma.BiPanelUpdateManyWithWhereWithoutDataSetInput[]
  deleteMany?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
}

export type BiPanelUncheckedUpdateManyWithoutDataSetNestedInput = {
  create?: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput> | Prisma.BiPanelCreateWithoutDataSetInput[] | Prisma.BiPanelUncheckedCreateWithoutDataSetInput[]
  connectOrCreate?: Prisma.BiPanelCreateOrConnectWithoutDataSetInput | Prisma.BiPanelCreateOrConnectWithoutDataSetInput[]
  upsert?: Prisma.BiPanelUpsertWithWhereUniqueWithoutDataSetInput | Prisma.BiPanelUpsertWithWhereUniqueWithoutDataSetInput[]
  createMany?: Prisma.BiPanelCreateManyDataSetInputEnvelope
  set?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  disconnect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  delete?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  connect?: Prisma.BiPanelWhereUniqueInput | Prisma.BiPanelWhereUniqueInput[]
  update?: Prisma.BiPanelUpdateWithWhereUniqueWithoutDataSetInput | Prisma.BiPanelUpdateWithWhereUniqueWithoutDataSetInput[]
  updateMany?: Prisma.BiPanelUpdateManyWithWhereWithoutDataSetInput | Prisma.BiPanelUpdateManyWithWhereWithoutDataSetInput[]
  deleteMany?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BiPanelCreateWithoutDashboardInput = {
  id?: string
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  dataSet?: Prisma.BiDatasetCreateNestedOneWithoutPanelsInput
}

export type BiPanelUncheckedCreateWithoutDashboardInput = {
  id?: string
  dataSetId?: string | null
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelCreateOrConnectWithoutDashboardInput = {
  where: Prisma.BiPanelWhereUniqueInput
  create: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput>
}

export type BiPanelCreateManyDashboardInputEnvelope = {
  data: Prisma.BiPanelCreateManyDashboardInput | Prisma.BiPanelCreateManyDashboardInput[]
  skipDuplicates?: boolean
}

export type BiPanelUpsertWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.BiPanelWhereUniqueInput
  update: Prisma.XOR<Prisma.BiPanelUpdateWithoutDashboardInput, Prisma.BiPanelUncheckedUpdateWithoutDashboardInput>
  create: Prisma.XOR<Prisma.BiPanelCreateWithoutDashboardInput, Prisma.BiPanelUncheckedCreateWithoutDashboardInput>
}

export type BiPanelUpdateWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.BiPanelWhereUniqueInput
  data: Prisma.XOR<Prisma.BiPanelUpdateWithoutDashboardInput, Prisma.BiPanelUncheckedUpdateWithoutDashboardInput>
}

export type BiPanelUpdateManyWithWhereWithoutDashboardInput = {
  where: Prisma.BiPanelScalarWhereInput
  data: Prisma.XOR<Prisma.BiPanelUpdateManyMutationInput, Prisma.BiPanelUncheckedUpdateManyWithoutDashboardInput>
}

export type BiPanelScalarWhereInput = {
  AND?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
  OR?: Prisma.BiPanelScalarWhereInput[]
  NOT?: Prisma.BiPanelScalarWhereInput | Prisma.BiPanelScalarWhereInput[]
  id?: Prisma.StringFilter<"BiPanel"> | string
  dashboardId?: Prisma.StringFilter<"BiPanel"> | string
  dataSetId?: Prisma.StringNullableFilter<"BiPanel"> | string | null
  title?: Prisma.StringFilter<"BiPanel"> | string
  chartType?: Prisma.StringFilter<"BiPanel"> | string
  config?: Prisma.JsonNullableFilter<"BiPanel">
  x?: Prisma.IntFilter<"BiPanel"> | number
  y?: Prisma.IntFilter<"BiPanel"> | number
  w?: Prisma.IntFilter<"BiPanel"> | number
  h?: Prisma.IntFilter<"BiPanel"> | number
  createdAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BiPanel"> | Date | string
}

export type BiPanelCreateWithoutDataSetInput = {
  id?: string
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  dashboard: Prisma.BiDashboardCreateNestedOneWithoutPanelsInput
}

export type BiPanelUncheckedCreateWithoutDataSetInput = {
  id?: string
  dashboardId: string
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelCreateOrConnectWithoutDataSetInput = {
  where: Prisma.BiPanelWhereUniqueInput
  create: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput>
}

export type BiPanelCreateManyDataSetInputEnvelope = {
  data: Prisma.BiPanelCreateManyDataSetInput | Prisma.BiPanelCreateManyDataSetInput[]
  skipDuplicates?: boolean
}

export type BiPanelUpsertWithWhereUniqueWithoutDataSetInput = {
  where: Prisma.BiPanelWhereUniqueInput
  update: Prisma.XOR<Prisma.BiPanelUpdateWithoutDataSetInput, Prisma.BiPanelUncheckedUpdateWithoutDataSetInput>
  create: Prisma.XOR<Prisma.BiPanelCreateWithoutDataSetInput, Prisma.BiPanelUncheckedCreateWithoutDataSetInput>
}

export type BiPanelUpdateWithWhereUniqueWithoutDataSetInput = {
  where: Prisma.BiPanelWhereUniqueInput
  data: Prisma.XOR<Prisma.BiPanelUpdateWithoutDataSetInput, Prisma.BiPanelUncheckedUpdateWithoutDataSetInput>
}

export type BiPanelUpdateManyWithWhereWithoutDataSetInput = {
  where: Prisma.BiPanelScalarWhereInput
  data: Prisma.XOR<Prisma.BiPanelUpdateManyMutationInput, Prisma.BiPanelUncheckedUpdateManyWithoutDataSetInput>
}

export type BiPanelCreateManyDashboardInput = {
  id?: string
  dataSetId?: string | null
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelUpdateWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dataSet?: Prisma.BiDatasetUpdateOneWithoutPanelsNestedInput
}

export type BiPanelUncheckedUpdateWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelUncheckedUpdateManyWithoutDashboardInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSetId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelCreateManyDataSetInput = {
  id?: string
  dashboardId: string
  title: string
  chartType?: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: number
  y?: number
  w?: number
  h?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BiPanelUpdateWithoutDataSetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dashboard?: Prisma.BiDashboardUpdateOneRequiredWithoutPanelsNestedInput
}

export type BiPanelUncheckedUpdateWithoutDataSetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BiPanelUncheckedUpdateManyWithoutDataSetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  chartType?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  x?: Prisma.IntFieldUpdateOperationsInput | number
  y?: Prisma.IntFieldUpdateOperationsInput | number
  w?: Prisma.IntFieldUpdateOperationsInput | number
  h?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BiPanelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  dataSetId?: boolean
  title?: boolean
  chartType?: boolean
  config?: boolean
  x?: boolean
  y?: boolean
  w?: boolean
  h?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}, ExtArgs["result"]["biPanel"]>

export type BiPanelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  dataSetId?: boolean
  title?: boolean
  chartType?: boolean
  config?: boolean
  x?: boolean
  y?: boolean
  w?: boolean
  h?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}, ExtArgs["result"]["biPanel"]>

export type BiPanelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dashboardId?: boolean
  dataSetId?: boolean
  title?: boolean
  chartType?: boolean
  config?: boolean
  x?: boolean
  y?: boolean
  w?: boolean
  h?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}, ExtArgs["result"]["biPanel"]>

export type BiPanelSelectScalar = {
  id?: boolean
  dashboardId?: boolean
  dataSetId?: boolean
  title?: boolean
  chartType?: boolean
  config?: boolean
  x?: boolean
  y?: boolean
  w?: boolean
  h?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BiPanelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dashboardId" | "dataSetId" | "title" | "chartType" | "config" | "x" | "y" | "w" | "h" | "createdAt" | "updatedAt", ExtArgs["result"]["biPanel"]>
export type BiPanelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}
export type BiPanelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}
export type BiPanelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.BiDashboardDefaultArgs<ExtArgs>
  dataSet?: boolean | Prisma.BiPanel$dataSetArgs<ExtArgs>
}

export type $BiPanelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BiPanel"
  objects: {
    dashboard: Prisma.$BiDashboardPayload<ExtArgs>
    dataSet: Prisma.$BiDatasetPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dashboardId: string
    dataSetId: string | null
    title: string
    chartType: string
    config: runtime.JsonValue | null
    x: number
    y: number
    w: number
    h: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["biPanel"]>
  composites: {}
}

export type BiPanelGetPayload<S extends boolean | null | undefined | BiPanelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BiPanelPayload, S>

export type BiPanelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BiPanelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BiPanelCountAggregateInputType | true
  }

export interface BiPanelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BiPanel'], meta: { name: 'BiPanel' } }
  /**
   * Find zero or one BiPanel that matches the filter.
   * @param {BiPanelFindUniqueArgs} args - Arguments to find a BiPanel
   * @example
   * // Get one BiPanel
   * const biPanel = await prisma.biPanel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BiPanelFindUniqueArgs>(args: Prisma.SelectSubset<T, BiPanelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BiPanel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BiPanelFindUniqueOrThrowArgs} args - Arguments to find a BiPanel
   * @example
   * // Get one BiPanel
   * const biPanel = await prisma.biPanel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BiPanelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BiPanelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiPanel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelFindFirstArgs} args - Arguments to find a BiPanel
   * @example
   * // Get one BiPanel
   * const biPanel = await prisma.biPanel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BiPanelFindFirstArgs>(args?: Prisma.SelectSubset<T, BiPanelFindFirstArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BiPanel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelFindFirstOrThrowArgs} args - Arguments to find a BiPanel
   * @example
   * // Get one BiPanel
   * const biPanel = await prisma.biPanel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BiPanelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BiPanelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BiPanels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BiPanels
   * const biPanels = await prisma.biPanel.findMany()
   * 
   * // Get first 10 BiPanels
   * const biPanels = await prisma.biPanel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const biPanelWithIdOnly = await prisma.biPanel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BiPanelFindManyArgs>(args?: Prisma.SelectSubset<T, BiPanelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BiPanel.
   * @param {BiPanelCreateArgs} args - Arguments to create a BiPanel.
   * @example
   * // Create one BiPanel
   * const BiPanel = await prisma.biPanel.create({
   *   data: {
   *     // ... data to create a BiPanel
   *   }
   * })
   * 
   */
  create<T extends BiPanelCreateArgs>(args: Prisma.SelectSubset<T, BiPanelCreateArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BiPanels.
   * @param {BiPanelCreateManyArgs} args - Arguments to create many BiPanels.
   * @example
   * // Create many BiPanels
   * const biPanel = await prisma.biPanel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BiPanelCreateManyArgs>(args?: Prisma.SelectSubset<T, BiPanelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BiPanels and returns the data saved in the database.
   * @param {BiPanelCreateManyAndReturnArgs} args - Arguments to create many BiPanels.
   * @example
   * // Create many BiPanels
   * const biPanel = await prisma.biPanel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BiPanels and only return the `id`
   * const biPanelWithIdOnly = await prisma.biPanel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BiPanelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BiPanelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BiPanel.
   * @param {BiPanelDeleteArgs} args - Arguments to delete one BiPanel.
   * @example
   * // Delete one BiPanel
   * const BiPanel = await prisma.biPanel.delete({
   *   where: {
   *     // ... filter to delete one BiPanel
   *   }
   * })
   * 
   */
  delete<T extends BiPanelDeleteArgs>(args: Prisma.SelectSubset<T, BiPanelDeleteArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BiPanel.
   * @param {BiPanelUpdateArgs} args - Arguments to update one BiPanel.
   * @example
   * // Update one BiPanel
   * const biPanel = await prisma.biPanel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BiPanelUpdateArgs>(args: Prisma.SelectSubset<T, BiPanelUpdateArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BiPanels.
   * @param {BiPanelDeleteManyArgs} args - Arguments to filter BiPanels to delete.
   * @example
   * // Delete a few BiPanels
   * const { count } = await prisma.biPanel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BiPanelDeleteManyArgs>(args?: Prisma.SelectSubset<T, BiPanelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiPanels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BiPanels
   * const biPanel = await prisma.biPanel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BiPanelUpdateManyArgs>(args: Prisma.SelectSubset<T, BiPanelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BiPanels and returns the data updated in the database.
   * @param {BiPanelUpdateManyAndReturnArgs} args - Arguments to update many BiPanels.
   * @example
   * // Update many BiPanels
   * const biPanel = await prisma.biPanel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BiPanels and only return the `id`
   * const biPanelWithIdOnly = await prisma.biPanel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BiPanelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BiPanelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BiPanel.
   * @param {BiPanelUpsertArgs} args - Arguments to update or create a BiPanel.
   * @example
   * // Update or create a BiPanel
   * const biPanel = await prisma.biPanel.upsert({
   *   create: {
   *     // ... data to create a BiPanel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BiPanel we want to update
   *   }
   * })
   */
  upsert<T extends BiPanelUpsertArgs>(args: Prisma.SelectSubset<T, BiPanelUpsertArgs<ExtArgs>>): Prisma.Prisma__BiPanelClient<runtime.Types.Result.GetResult<Prisma.$BiPanelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BiPanels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelCountArgs} args - Arguments to filter BiPanels to count.
   * @example
   * // Count the number of BiPanels
   * const count = await prisma.biPanel.count({
   *   where: {
   *     // ... the filter for the BiPanels we want to count
   *   }
   * })
  **/
  count<T extends BiPanelCountArgs>(
    args?: Prisma.Subset<T, BiPanelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BiPanelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BiPanel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BiPanelAggregateArgs>(args: Prisma.Subset<T, BiPanelAggregateArgs>): Prisma.PrismaPromise<GetBiPanelAggregateType<T>>

  /**
   * Group by BiPanel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BiPanelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BiPanelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BiPanelGroupByArgs['orderBy'] }
      : { orderBy?: BiPanelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BiPanelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBiPanelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BiPanel model
 */
readonly fields: BiPanelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BiPanel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BiPanelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dashboard<T extends Prisma.BiDashboardDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiDashboardDefaultArgs<ExtArgs>>): Prisma.Prisma__BiDashboardClient<runtime.Types.Result.GetResult<Prisma.$BiDashboardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  dataSet<T extends Prisma.BiPanel$dataSetArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BiPanel$dataSetArgs<ExtArgs>>): Prisma.Prisma__BiDatasetClient<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BiPanel model
 */
export interface BiPanelFieldRefs {
  readonly id: Prisma.FieldRef<"BiPanel", 'String'>
  readonly dashboardId: Prisma.FieldRef<"BiPanel", 'String'>
  readonly dataSetId: Prisma.FieldRef<"BiPanel", 'String'>
  readonly title: Prisma.FieldRef<"BiPanel", 'String'>
  readonly chartType: Prisma.FieldRef<"BiPanel", 'String'>
  readonly config: Prisma.FieldRef<"BiPanel", 'Json'>
  readonly x: Prisma.FieldRef<"BiPanel", 'Int'>
  readonly y: Prisma.FieldRef<"BiPanel", 'Int'>
  readonly w: Prisma.FieldRef<"BiPanel", 'Int'>
  readonly h: Prisma.FieldRef<"BiPanel", 'Int'>
  readonly createdAt: Prisma.FieldRef<"BiPanel", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BiPanel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BiPanel findUnique
 */
export type BiPanelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter, which BiPanel to fetch.
   */
  where: Prisma.BiPanelWhereUniqueInput
}

/**
 * BiPanel findUniqueOrThrow
 */
export type BiPanelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter, which BiPanel to fetch.
   */
  where: Prisma.BiPanelWhereUniqueInput
}

/**
 * BiPanel findFirst
 */
export type BiPanelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter, which BiPanel to fetch.
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiPanels to fetch.
   */
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiPanels.
   */
  cursor?: Prisma.BiPanelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiPanels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiPanels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiPanels.
   */
  distinct?: Prisma.BiPanelScalarFieldEnum | Prisma.BiPanelScalarFieldEnum[]
}

/**
 * BiPanel findFirstOrThrow
 */
export type BiPanelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter, which BiPanel to fetch.
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiPanels to fetch.
   */
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BiPanels.
   */
  cursor?: Prisma.BiPanelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiPanels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiPanels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiPanels.
   */
  distinct?: Prisma.BiPanelScalarFieldEnum | Prisma.BiPanelScalarFieldEnum[]
}

/**
 * BiPanel findMany
 */
export type BiPanelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter, which BiPanels to fetch.
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BiPanels to fetch.
   */
  orderBy?: Prisma.BiPanelOrderByWithRelationInput | Prisma.BiPanelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BiPanels.
   */
  cursor?: Prisma.BiPanelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BiPanels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BiPanels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BiPanels.
   */
  distinct?: Prisma.BiPanelScalarFieldEnum | Prisma.BiPanelScalarFieldEnum[]
}

/**
 * BiPanel create
 */
export type BiPanelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * The data needed to create a BiPanel.
   */
  data: Prisma.XOR<Prisma.BiPanelCreateInput, Prisma.BiPanelUncheckedCreateInput>
}

/**
 * BiPanel createMany
 */
export type BiPanelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BiPanels.
   */
  data: Prisma.BiPanelCreateManyInput | Prisma.BiPanelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BiPanel createManyAndReturn
 */
export type BiPanelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * The data used to create many BiPanels.
   */
  data: Prisma.BiPanelCreateManyInput | Prisma.BiPanelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BiPanel update
 */
export type BiPanelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * The data needed to update a BiPanel.
   */
  data: Prisma.XOR<Prisma.BiPanelUpdateInput, Prisma.BiPanelUncheckedUpdateInput>
  /**
   * Choose, which BiPanel to update.
   */
  where: Prisma.BiPanelWhereUniqueInput
}

/**
 * BiPanel updateMany
 */
export type BiPanelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BiPanels.
   */
  data: Prisma.XOR<Prisma.BiPanelUpdateManyMutationInput, Prisma.BiPanelUncheckedUpdateManyInput>
  /**
   * Filter which BiPanels to update
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * Limit how many BiPanels to update.
   */
  limit?: number
}

/**
 * BiPanel updateManyAndReturn
 */
export type BiPanelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * The data used to update BiPanels.
   */
  data: Prisma.XOR<Prisma.BiPanelUpdateManyMutationInput, Prisma.BiPanelUncheckedUpdateManyInput>
  /**
   * Filter which BiPanels to update
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * Limit how many BiPanels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BiPanel upsert
 */
export type BiPanelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * The filter to search for the BiPanel to update in case it exists.
   */
  where: Prisma.BiPanelWhereUniqueInput
  /**
   * In case the BiPanel found by the `where` argument doesn't exist, create a new BiPanel with this data.
   */
  create: Prisma.XOR<Prisma.BiPanelCreateInput, Prisma.BiPanelUncheckedCreateInput>
  /**
   * In case the BiPanel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BiPanelUpdateInput, Prisma.BiPanelUncheckedUpdateInput>
}

/**
 * BiPanel delete
 */
export type BiPanelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
  /**
   * Filter which BiPanel to delete.
   */
  where: Prisma.BiPanelWhereUniqueInput
}

/**
 * BiPanel deleteMany
 */
export type BiPanelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BiPanels to delete
   */
  where?: Prisma.BiPanelWhereInput
  /**
   * Limit how many BiPanels to delete.
   */
  limit?: number
}

/**
 * BiPanel.dataSet
 */
export type BiPanel$dataSetArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  where?: Prisma.BiDatasetWhereInput
}

/**
 * BiPanel without action
 */
export type BiPanelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiPanel
   */
  select?: Prisma.BiPanelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiPanel
   */
  omit?: Prisma.BiPanelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiPanelInclude<ExtArgs> | null
}
