
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  fullName: string | null
  avatar: string | null
  userName: string | null
  email: string | null
  passwordHash: string | null
  isSuperAdmin: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  fullName: string | null
  avatar: string | null
  userName: string | null
  email: string | null
  passwordHash: string | null
  isSuperAdmin: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  fullName: number
  avatar: number
  userName: number
  email: number
  passwordHash: number
  isSuperAdmin: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  fullName?: true
  avatar?: true
  userName?: true
  email?: true
  passwordHash?: true
  isSuperAdmin?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  fullName?: true
  avatar?: true
  userName?: true
  email?: true
  passwordHash?: true
  isSuperAdmin?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  fullName?: true
  avatar?: true
  userName?: true
  email?: true
  passwordHash?: true
  isSuperAdmin?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  fullName: string | null
  avatar: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin: boolean
  createdAt: Date
  updatedAt: Date
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  fullName?: Prisma.StringNullableFilter<"User"> | string | null
  avatar?: Prisma.StringNullableFilter<"User"> | string | null
  userName?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringFilter<"User"> | string
  passwordHash?: Prisma.StringFilter<"User"> | string
  isSuperAdmin?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  userRoles?: Prisma.UserRoleListRelationFilter
  biDashboards?: Prisma.BiDashboardListRelationFilter
  biDashboardMembers?: Prisma.BiDashboardMemberListRelationFilter
  biDatasets?: Prisma.BiDatasetListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  isSuperAdmin?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userRoles?: Prisma.UserRoleOrderByRelationAggregateInput
  biDashboards?: Prisma.BiDashboardOrderByRelationAggregateInput
  biDashboardMembers?: Prisma.BiDashboardMemberOrderByRelationAggregateInput
  biDatasets?: Prisma.BiDatasetOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userName?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  fullName?: Prisma.StringNullableFilter<"User"> | string | null
  avatar?: Prisma.StringNullableFilter<"User"> | string | null
  passwordHash?: Prisma.StringFilter<"User"> | string
  isSuperAdmin?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  userRoles?: Prisma.UserRoleListRelationFilter
  biDashboards?: Prisma.BiDashboardListRelationFilter
  biDashboardMembers?: Prisma.BiDashboardMemberListRelationFilter
  biDatasets?: Prisma.BiDatasetListRelationFilter
}, "id" | "userName" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  isSuperAdmin?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  fullName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  avatar?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  userName?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  passwordHash?: Prisma.StringWithAggregatesFilter<"User"> | string
  isSuperAdmin?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
}

export type UserCreateInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  isSuperAdmin?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  isSuperAdmin?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  isSuperAdmin?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UserCreateNestedOneWithoutUserRolesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserRolesInput, Prisma.UserUncheckedCreateWithoutUserRolesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserRolesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutUserRolesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserRolesInput, Prisma.UserUncheckedCreateWithoutUserRolesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserRolesInput
  upsert?: Prisma.UserUpsertWithoutUserRolesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutUserRolesInput, Prisma.UserUpdateWithoutUserRolesInput>, Prisma.UserUncheckedUpdateWithoutUserRolesInput>
}

export type UserCreateNestedOneWithoutBiDashboardsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardsInput, Prisma.UserUncheckedCreateWithoutBiDashboardsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDashboardsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutBiDashboardsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardsInput, Prisma.UserUncheckedCreateWithoutBiDashboardsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDashboardsInput
  upsert?: Prisma.UserUpsertWithoutBiDashboardsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutBiDashboardsInput, Prisma.UserUpdateWithoutBiDashboardsInput>, Prisma.UserUncheckedUpdateWithoutBiDashboardsInput>
}

export type UserCreateNestedOneWithoutBiDashboardMembersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardMembersInput, Prisma.UserUncheckedCreateWithoutBiDashboardMembersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDashboardMembersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutBiDashboardMembersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardMembersInput, Prisma.UserUncheckedCreateWithoutBiDashboardMembersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDashboardMembersInput
  upsert?: Prisma.UserUpsertWithoutBiDashboardMembersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutBiDashboardMembersInput, Prisma.UserUpdateWithoutBiDashboardMembersInput>, Prisma.UserUncheckedUpdateWithoutBiDashboardMembersInput>
}

export type UserCreateNestedOneWithoutBiDatasetsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDatasetsInput, Prisma.UserUncheckedCreateWithoutBiDatasetsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDatasetsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutBiDatasetsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutBiDatasetsInput, Prisma.UserUncheckedCreateWithoutBiDatasetsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutBiDatasetsInput
  upsert?: Prisma.UserUpsertWithoutBiDatasetsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutBiDatasetsInput, Prisma.UserUpdateWithoutBiDatasetsInput>, Prisma.UserUncheckedUpdateWithoutBiDatasetsInput>
}

export type UserCreateWithoutUserRolesInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  biDashboards?: Prisma.BiDashboardCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutUserRolesInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  biDashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutUserRolesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutUserRolesInput, Prisma.UserUncheckedCreateWithoutUserRolesInput>
}

export type UserUpsertWithoutUserRolesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutUserRolesInput, Prisma.UserUncheckedUpdateWithoutUserRolesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutUserRolesInput, Prisma.UserUncheckedCreateWithoutUserRolesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutUserRolesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutUserRolesInput, Prisma.UserUncheckedUpdateWithoutUserRolesInput>
}

export type UserUpdateWithoutUserRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  biDashboards?: Prisma.BiDashboardUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutUserRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  biDashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutBiDashboardsInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutBiDashboardsInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutBiDashboardsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardsInput, Prisma.UserUncheckedCreateWithoutBiDashboardsInput>
}

export type UserUpsertWithoutBiDashboardsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutBiDashboardsInput, Prisma.UserUncheckedUpdateWithoutBiDashboardsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardsInput, Prisma.UserUncheckedCreateWithoutBiDashboardsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutBiDashboardsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutBiDashboardsInput, Prisma.UserUncheckedUpdateWithoutBiDashboardsInput>
}

export type UserUpdateWithoutBiDashboardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutBiDashboardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutBiDashboardMembersInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutBiDashboardMembersInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutUserInput
  biDatasets?: Prisma.BiDatasetUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutBiDashboardMembersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardMembersInput, Prisma.UserUncheckedCreateWithoutBiDashboardMembersInput>
}

export type UserUpsertWithoutBiDashboardMembersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutBiDashboardMembersInput, Prisma.UserUncheckedUpdateWithoutBiDashboardMembersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDashboardMembersInput, Prisma.UserUncheckedCreateWithoutBiDashboardMembersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutBiDashboardMembersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutBiDashboardMembersInput, Prisma.UserUncheckedUpdateWithoutBiDashboardMembersInput>
}

export type UserUpdateWithoutBiDashboardMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutBiDashboardMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutUserNestedInput
  biDatasets?: Prisma.BiDatasetUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutBiDatasetsInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutBiDatasetsInput = {
  id?: string
  fullName?: string | null
  avatar?: string | null
  userName: string
  email: string
  passwordHash: string
  isSuperAdmin?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.UserRoleUncheckedCreateNestedManyWithoutUserInput
  biDashboards?: Prisma.BiDashboardUncheckedCreateNestedManyWithoutUserInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutBiDatasetsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDatasetsInput, Prisma.UserUncheckedCreateWithoutBiDatasetsInput>
}

export type UserUpsertWithoutBiDatasetsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutBiDatasetsInput, Prisma.UserUncheckedUpdateWithoutBiDatasetsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutBiDatasetsInput, Prisma.UserUncheckedCreateWithoutBiDatasetsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutBiDatasetsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutBiDatasetsInput, Prisma.UserUncheckedUpdateWithoutBiDatasetsInput>
}

export type UserUpdateWithoutBiDatasetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutBiDatasetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  isSuperAdmin?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.UserRoleUncheckedUpdateManyWithoutUserNestedInput
  biDashboards?: Prisma.BiDashboardUncheckedUpdateManyWithoutUserNestedInput
  biDashboardMembers?: Prisma.BiDashboardMemberUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  userRoles: number
  biDashboards: number
  biDashboardMembers: number
  biDatasets: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userRoles?: boolean | UserCountOutputTypeCountUserRolesArgs
  biDashboards?: boolean | UserCountOutputTypeCountBiDashboardsArgs
  biDashboardMembers?: boolean | UserCountOutputTypeCountBiDashboardMembersArgs
  biDatasets?: boolean | UserCountOutputTypeCountBiDatasetsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountUserRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRoleWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountBiDashboardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDashboardWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountBiDashboardMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDashboardMemberWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountBiDatasetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BiDatasetWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  avatar?: boolean
  userName?: boolean
  email?: boolean
  passwordHash?: boolean
  isSuperAdmin?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userRoles?: boolean | Prisma.User$userRolesArgs<ExtArgs>
  biDashboards?: boolean | Prisma.User$biDashboardsArgs<ExtArgs>
  biDashboardMembers?: boolean | Prisma.User$biDashboardMembersArgs<ExtArgs>
  biDatasets?: boolean | Prisma.User$biDatasetsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  avatar?: boolean
  userName?: boolean
  email?: boolean
  passwordHash?: boolean
  isSuperAdmin?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  avatar?: boolean
  userName?: boolean
  email?: boolean
  passwordHash?: boolean
  isSuperAdmin?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  fullName?: boolean
  avatar?: boolean
  userName?: boolean
  email?: boolean
  passwordHash?: boolean
  isSuperAdmin?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fullName" | "avatar" | "userName" | "email" | "passwordHash" | "isSuperAdmin" | "createdAt" | "updatedAt", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userRoles?: boolean | Prisma.User$userRolesArgs<ExtArgs>
  biDashboards?: boolean | Prisma.User$biDashboardsArgs<ExtArgs>
  biDashboardMembers?: boolean | Prisma.User$biDashboardMembersArgs<ExtArgs>
  biDatasets?: boolean | Prisma.User$biDatasetsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    userRoles: Prisma.$UserRolePayload<ExtArgs>[]
    biDashboards: Prisma.$BiDashboardPayload<ExtArgs>[]
    biDashboardMembers: Prisma.$BiDashboardMemberPayload<ExtArgs>[]
    biDatasets: Prisma.$BiDatasetPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fullName: string | null
    avatar: string | null
    userName: string
    email: string
    passwordHash: string
    isSuperAdmin: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userRoles<T extends Prisma.User$userRolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$userRolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  biDashboards<T extends Prisma.User$biDashboardsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$biDashboardsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDashboardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  biDashboardMembers<T extends Prisma.User$biDashboardMembersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$biDashboardMembersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDashboardMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  biDatasets<T extends Prisma.User$biDatasetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$biDatasetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BiDatasetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly fullName: Prisma.FieldRef<"User", 'String'>
  readonly avatar: Prisma.FieldRef<"User", 'String'>
  readonly userName: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly passwordHash: Prisma.FieldRef<"User", 'String'>
  readonly isSuperAdmin: Prisma.FieldRef<"User", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.userRoles
 */
export type User$userRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  where?: Prisma.UserRoleWhereInput
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[]
  cursor?: Prisma.UserRoleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserRoleScalarFieldEnum | Prisma.UserRoleScalarFieldEnum[]
}

/**
 * User.biDashboards
 */
export type User$biDashboardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDashboard
   */
  select?: Prisma.BiDashboardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDashboard
   */
  omit?: Prisma.BiDashboardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDashboardInclude<ExtArgs> | null
  where?: Prisma.BiDashboardWhereInput
  orderBy?: Prisma.BiDashboardOrderByWithRelationInput | Prisma.BiDashboardOrderByWithRelationInput[]
  cursor?: Prisma.BiDashboardWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiDashboardScalarFieldEnum | Prisma.BiDashboardScalarFieldEnum[]
}

/**
 * User.biDashboardMembers
 */
export type User$biDashboardMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDashboardMember
   */
  select?: Prisma.BiDashboardMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDashboardMember
   */
  omit?: Prisma.BiDashboardMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDashboardMemberInclude<ExtArgs> | null
  where?: Prisma.BiDashboardMemberWhereInput
  orderBy?: Prisma.BiDashboardMemberOrderByWithRelationInput | Prisma.BiDashboardMemberOrderByWithRelationInput[]
  cursor?: Prisma.BiDashboardMemberWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiDashboardMemberScalarFieldEnum | Prisma.BiDashboardMemberScalarFieldEnum[]
}

/**
 * User.biDatasets
 */
export type User$biDatasetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BiDataset
   */
  select?: Prisma.BiDatasetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BiDataset
   */
  omit?: Prisma.BiDatasetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BiDatasetInclude<ExtArgs> | null
  where?: Prisma.BiDatasetWhereInput
  orderBy?: Prisma.BiDatasetOrderByWithRelationInput | Prisma.BiDatasetOrderByWithRelationInput[]
  cursor?: Prisma.BiDatasetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BiDatasetScalarFieldEnum | Prisma.BiDatasetScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
