name: Deploy to Production

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: ~/PORTOFOLIO
        run: |
          git pull origin prod
          bun install
          bun db:generate
          bun run build
          pm2 restart 2
